// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: relation.proto

package groupmemberservice

import (
	"context"

	"IMM/rpc/relation/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyToJoinGroupReq      = relation.ApplyToJoinGroupReq
	CommonResponse           = relation.CommonResponse
	GetGroupJoinRequestsReq  = relation.GetGroupJoinRequestsReq
	GetGroupJoinRequestsResp = relation.GetGroupJoinRequestsResp
	GetGroupMembersReq       = relation.GetGroupMembersReq
	GetGroupMembersResp      = relation.GetGroupMembersResp
	InviteToGroupReq         = relation.InviteToGroupReq
	ProcessGroupJoinReq      = relation.ProcessGroupJoinReq
	QuitGroupReq             = relation.QuitGroupReq
	RemoveGroupMemberReq     = relation.RemoveGroupMemberReq
	SetGroupMemberRoleReq    = relation.SetGroupMemberRoleReq
	SetGroupNickReq          = relation.SetGroupNickReq

	GroupMemberService interface {
		// ----- 群成员管理 -----
		ApplyToJoinGroup(ctx context.Context, in *ApplyToJoinGroupReq, opts ...grpc.CallOption) (*CommonResponse, error)
		ProcessGroupJoin(ctx context.Context, in *ProcessGroupJoinReq, opts ...grpc.CallOption) (*CommonResponse, error)
		InviteToGroup(ctx context.Context, in *InviteToGroupReq, opts ...grpc.CallOption) (*CommonResponse, error)
		QuitGroup(ctx context.Context, in *QuitGroupReq, opts ...grpc.CallOption) (*CommonResponse, error)
		RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, opts ...grpc.CallOption) (*CommonResponse, error)
		SetGroupMemberRole(ctx context.Context, in *SetGroupMemberRoleReq, opts ...grpc.CallOption) (*CommonResponse, error)
		SetGroupNick(ctx context.Context, in *SetGroupNickReq, opts ...grpc.CallOption) (*CommonResponse, error)
		GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error)
		GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsResp, error)
	}

	defaultGroupMemberService struct {
		cli zrpc.Client
	}
)

func NewGroupMemberService(cli zrpc.Client) GroupMemberService {
	return &defaultGroupMemberService{
		cli: cli,
	}
}

// ----- 群成员管理 -----
func (m *defaultGroupMemberService) ApplyToJoinGroup(ctx context.Context, in *ApplyToJoinGroupReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewGroupMemberServiceClient(m.cli.Conn())
	return client.ApplyToJoinGroup(ctx, in, opts...)
}

func (m *defaultGroupMemberService) ProcessGroupJoin(ctx context.Context, in *ProcessGroupJoinReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewGroupMemberServiceClient(m.cli.Conn())
	return client.ProcessGroupJoin(ctx, in, opts...)
}

func (m *defaultGroupMemberService) InviteToGroup(ctx context.Context, in *InviteToGroupReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewGroupMemberServiceClient(m.cli.Conn())
	return client.InviteToGroup(ctx, in, opts...)
}

func (m *defaultGroupMemberService) QuitGroup(ctx context.Context, in *QuitGroupReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewGroupMemberServiceClient(m.cli.Conn())
	return client.QuitGroup(ctx, in, opts...)
}

func (m *defaultGroupMemberService) RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewGroupMemberServiceClient(m.cli.Conn())
	return client.RemoveGroupMember(ctx, in, opts...)
}

func (m *defaultGroupMemberService) SetGroupMemberRole(ctx context.Context, in *SetGroupMemberRoleReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewGroupMemberServiceClient(m.cli.Conn())
	return client.SetGroupMemberRole(ctx, in, opts...)
}

func (m *defaultGroupMemberService) SetGroupNick(ctx context.Context, in *SetGroupNickReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewGroupMemberServiceClient(m.cli.Conn())
	return client.SetGroupNick(ctx, in, opts...)
}

func (m *defaultGroupMemberService) GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error) {
	client := relation.NewGroupMemberServiceClient(m.cli.Conn())
	return client.GetGroupMembers(ctx, in, opts...)
}

func (m *defaultGroupMemberService) GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsResp, error) {
	client := relation.NewGroupMemberServiceClient(m.cli.Conn())
	return client.GetGroupJoinRequests(ctx, in, opts...)
}
