// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	chat "IMM/api/internal/handler/chat"
	friend "IMM/api/internal/handler/friend"
	user "IMM/api/internal/handler/user"
	"IMM/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/heart",
				Handler: HeartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/GetUnreadGroupMsgNumber",
				Handler: chat.GetUnreadGroupMsgNumberHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/GetUnreadPrivateMsgNumber",
				Handler: chat.GetUnreadPrivateMsgNumberHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/chat"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/apply_list",
				Handler: friend.GetFriendRequestListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: friend.DeleteFriendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: friend.GetFriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/remark",
				Handler: friend.SetFriendMarkHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/request",
				Handler: friend.FriendRequestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/request_handle",
				Handler: friend.HandleFriendRequestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/search",
				Handler: friend.SearchFriendHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/friend"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.GetInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update/avatar",
				Handler: user.UpdateAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update/email",
				Handler: user.UpdateEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update/info",
				Handler: user.UpdateInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update/password",
				Handler: user.UpdatePasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/user"),
	)
}
