// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: chat.proto

package server

import (
	"context"

	"IMM/rpc/chat/chat"
	"IMM/rpc/chat/internal/logic"
	"IMM/rpc/chat/internal/svc"
)

type ChatServiceServer struct {
	svcCtx *svc.ServiceContext
	chat.UnimplementedChatServiceServer
}

func NewChatServiceServer(svcCtx *svc.ServiceContext) *ChatServiceServer {
	return &ChatServiceServer{
		svcCtx: svcCtx,
	}
}

// 发送私聊消息
func (s *ChatServiceServer) SendPrivateMessage(ctx context.Context, in *chat.SendPrivateMessageReq) (*chat.SendMessageResp, error) {
	l := logic.NewSendPrivateMessageLogic(ctx, s.svcCtx)
	return l.SendPrivateMessage(in)
}

// 发送群聊消息
func (s *ChatServiceServer) SendGroupMessage(ctx context.Context, in *chat.SendGroupMessageReq) (*chat.SendMessageResp, error) {
	l := logic.NewSendGroupMessageLogic(ctx, s.svcCtx)
	return l.SendGroupMessage(in)
}

// 拉取历史消息
func (s *ChatServiceServer) GetHistoryChatMessage(ctx context.Context, in *chat.GetChatHistoryMessagesReq) (*chat.CommonResponse, error) {
	l := logic.NewGetHistoryChatMessageLogic(ctx, s.svcCtx)
	return l.GetHistoryChatMessage(in)
}

func (s *ChatServiceServer) GetHistoryGroupMessages(ctx context.Context, in *chat.GetGroupHistoryMessagesReq) (*chat.CommonResponse, error) {
	l := logic.NewGetHistoryGroupMessagesLogic(ctx, s.svcCtx)
	return l.GetHistoryGroupMessages(in)
}

// 拉取新消息
func (s *ChatServiceServer) GetUnreadChatMessage(ctx context.Context, in *chat.GetChatUnreadMessagesReq) (*chat.CommonResponse, error) {
	l := logic.NewGetUnreadChatMessageLogic(ctx, s.svcCtx)
	return l.GetUnreadChatMessage(in)
}

func (s *ChatServiceServer) GetUnreadGroupMessages(ctx context.Context, in *chat.GetGroupUnreadMessagesReq) (*chat.CommonResponse, error) {
	l := logic.NewGetUnreadGroupMessagesLogic(ctx, s.svcCtx)
	return l.GetUnreadGroupMessages(in)
}

// 获取新消息数量
func (s *ChatServiceServer) GetNewChatMessageNumber(ctx context.Context, in *chat.GetChatNewMessagesNumberReq) (*chat.GetMessageNumberResp, error) {
	l := logic.NewGetNewChatMessageNumberLogic(ctx, s.svcCtx)
	return l.GetNewChatMessageNumber(in)
}

func (s *ChatServiceServer) GetNewGroupMessageNumber(ctx context.Context, in *chat.GetGroupNewMessagesNumberReq) (*chat.GetMessageNumberResp, error) {
	l := logic.NewGetNewGroupMessageNumberLogic(ctx, s.svcCtx)
	return l.GetNewGroupMessageNumber(in)
}

// 更新用户最后已读信息
func (s *ChatServiceServer) UpdateChatMsgLastRead(ctx context.Context, in *chat.UpdateLastReadMsgRep) (*chat.CommonResponse, error) {
	l := logic.NewUpdateChatMsgLastReadLogic(ctx, s.svcCtx)
	return l.UpdateChatMsgLastRead(in)
}

func (s *ChatServiceServer) UpdataGroupMsgLastRead(ctx context.Context, in *chat.UpdateLastReadMsgRep) (*chat.CommonResponse, error) {
	l := logic.NewUpdataGroupMsgLastReadLogic(ctx, s.svcCtx)
	return l.UpdataGroupMsgLastRead(in)
}
