// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // http
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`  // 返回消息, 由GateWay进行封装推送
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetAgentInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentPrompt   string                 `protobuf:"bytes,3,opt,name=agent_prompt,json=agentPrompt,proto3" json:"agent_prompt,omitempty"`
	AgentAvatar   string                 `protobuf:"bytes,4,opt,name=agent_avatar,json=agentAvatar,proto3" json:"agent_avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAgentInfoReq) Reset() {
	*x = SetAgentInfoReq{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAgentInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgentInfoReq) ProtoMessage() {}

func (x *SetAgentInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgentInfoReq.ProtoReflect.Descriptor instead.
func (*SetAgentInfoReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *SetAgentInfoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetAgentInfoReq) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *SetAgentInfoReq) GetAgentPrompt() string {
	if x != nil {
		return x.AgentPrompt
	}
	return ""
}

func (x *SetAgentInfoReq) GetAgentAvatar() string {
	if x != nil {
		return x.AgentAvatar
	}
	return ""
}

type GetAgentInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentInfoReq) Reset() {
	*x = GetAgentInfoReq{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentInfoReq) ProtoMessage() {}

func (x *GetAgentInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentInfoReq.ProtoReflect.Descriptor instead.
func (*GetAgentInfoReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentInfoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAgentInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentPrompt   string                 `protobuf:"bytes,3,opt,name=agent_prompt,json=agentPrompt,proto3" json:"agent_prompt,omitempty"`
	AgentAvatar   string                 `protobuf:"bytes,4,opt,name=agent_avatar,json=agentAvatar,proto3" json:"agent_avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentInfoResp) Reset() {
	*x = GetAgentInfoResp{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentInfoResp) ProtoMessage() {}

func (x *GetAgentInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentInfoResp.ProtoReflect.Descriptor instead.
func (*GetAgentInfoResp) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentInfoResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAgentInfoResp) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *GetAgentInfoResp) GetAgentPrompt() string {
	if x != nil {
		return x.AgentPrompt
	}
	return ""
}

func (x *GetAgentInfoResp) GetAgentAvatar() string {
	if x != nil {
		return x.AgentAvatar
	}
	return ""
}

// 发送消息
type SendMessageToAiReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    uint64                 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId   uint64                 `protobuf:"varint,4,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageToAiReq) Reset() {
	*x = SendMessageToAiReq{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageToAiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToAiReq) ProtoMessage() {}

func (x *SendMessageToAiReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToAiReq.ProtoReflect.Descriptor instead.
func (*SendMessageToAiReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageToAiReq) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *SendMessageToAiReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SendMessageToAiReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageToAiReq) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

// 发送消息响应
type SendMessageResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          uint64                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SendTime       int64                  `protobuf:"varint,2,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	CommonResponse *CommonResponse        `protobuf:"bytes,3,opt,name=CommonResponse,proto3" json:"CommonResponse,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageResp) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendMessageResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *SendMessageResp) GetCommonResponse() *CommonResponse {
	if x != nil {
		return x.CommonResponse
	}
	return nil
}

// ---------- 拉取历史对话（接收消息） ----------
// 拉取已读消息
type GetChatHistoryMessagesFromAIReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 当前用户ID（用于鉴权）
	StartMsgId    uint64                 `protobuf:"varint,4,opt,name=start_msg_id,json=startMsgId,proto3" json:"start_msg_id,omitempty"` // 起始消息ID 逆序往上
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                               // 每次拉取数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryMessagesFromAIReq) Reset() {
	*x = GetChatHistoryMessagesFromAIReq{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryMessagesFromAIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryMessagesFromAIReq) ProtoMessage() {}

func (x *GetChatHistoryMessagesFromAIReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryMessagesFromAIReq.ProtoReflect.Descriptor instead.
func (*GetChatHistoryMessagesFromAIReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatHistoryMessagesFromAIReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetChatHistoryMessagesFromAIReq) GetStartMsgId() uint64 {
	if x != nil {
		return x.StartMsgId
	}
	return 0
}

func (x *GetChatHistoryMessagesFromAIReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 拉取未读消息
type GetChatUnreadMessagesFromAIReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 当前用户ID（用于鉴权）
	StartMsgId    uint64                 `protobuf:"varint,4,opt,name=start_msg_id,json=startMsgId,proto3" json:"start_msg_id,omitempty"` // 起始消息ID，顺序往下
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                               // 每次拉取数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatUnreadMessagesFromAIReq) Reset() {
	*x = GetChatUnreadMessagesFromAIReq{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatUnreadMessagesFromAIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatUnreadMessagesFromAIReq) ProtoMessage() {}

func (x *GetChatUnreadMessagesFromAIReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatUnreadMessagesFromAIReq.ProtoReflect.Descriptor instead.
func (*GetChatUnreadMessagesFromAIReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatUnreadMessagesFromAIReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetChatUnreadMessagesFromAIReq) GetStartMsgId() uint64 {
	if x != nil {
		return x.StartMsgId
	}
	return 0
}

func (x *GetChatUnreadMessagesFromAIReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdateLastReadMsgRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	MsgId         uint64                 `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastReadMsgRep) Reset() {
	*x = UpdateLastReadMsgRep{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastReadMsgRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastReadMsgRep) ProtoMessage() {}

func (x *UpdateLastReadMsgRep) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastReadMsgRep.ProtoReflect.Descriptor instead.
func (*UpdateLastReadMsgRep) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLastReadMsgRep) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateLastReadMsgRep) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *UpdateLastReadMsgRep) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"8\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x8f\x01\n" +
	"\x0fSetAgentInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12!\n" +
	"\fagent_prompt\x18\x03 \x01(\tR\vagentPrompt\x12!\n" +
	"\fagent_avatar\x18\x04 \x01(\tR\vagentAvatar\"*\n" +
	"\x0fGetAgentInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x90\x01\n" +
	"\x10GetAgentInfoResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12!\n" +
	"\fagent_prompt\x18\x03 \x01(\tR\vagentPrompt\x12!\n" +
	"\fagent_avatar\x18\x04 \x01(\tR\vagentAvatar\"\x8f\x01\n" +
	"\x12SendMessageToAiReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x04R\n" +
	"fromUserId\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x04 \x01(\x04R\vclientMsgId\"\x81\x01\n" +
	"\x0fSendMessageResp\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x04R\x05msgId\x12\x1b\n" +
	"\tsend_time\x18\x02 \x01(\x03R\bsendTime\x12:\n" +
	"\x0eCommonResponse\x18\x03 \x01(\v2\x12.ai.CommonResponseR\x0eCommonResponse\"r\n" +
	"\x1fGetChatHistoryMessagesFromAIReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12 \n" +
	"\fstart_msg_id\x18\x04 \x01(\x04R\n" +
	"startMsgId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"q\n" +
	"\x1eGetChatUnreadMessagesFromAIReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12 \n" +
	"\fstart_msg_id\x18\x04 \x01(\x04R\n" +
	"startMsgId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"c\n" +
	"\x14UpdateLastReadMsgRep\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x04R\x05msgId2\xa7\x03\n" +
	"\vChatService\x127\n" +
	"\fSetAgentInfo\x12\x13.ai.SetAgentInfoReq\x1a\x12.ai.CommonResponse\x129\n" +
	"\fGetAgentInfo\x12\x13.ai.GetAgentInfoReq\x1a\x14.ai.GetAgentInfoResp\x12A\n" +
	"\x12SendPrivateMessage\x12\x16.ai.SendMessageToAiReq\x1a\x13.ai.SendMessageResp\x12N\n" +
	"\x13GetHistoryAiMessage\x12#.ai.GetChatHistoryMessagesFromAIReq\x1a\x12.ai.CommonResponse\x12L\n" +
	"\x12GetUnreadAiMessage\x12\".ai.GetChatUnreadMessagesFromAIReq\x1a\x12.ai.CommonResponse\x12C\n" +
	"\x13UpdateAiMsgLastRead\x12\x18.ai.UpdateLastReadMsgRep\x1a\x12.ai.CommonResponseB\x06Z\x04./aib\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ai_proto_goTypes = []any{
	(*CommonResponse)(nil),                  // 0: ai.CommonResponse
	(*SetAgentInfoReq)(nil),                 // 1: ai.SetAgentInfoReq
	(*GetAgentInfoReq)(nil),                 // 2: ai.GetAgentInfoReq
	(*GetAgentInfoResp)(nil),                // 3: ai.GetAgentInfoResp
	(*SendMessageToAiReq)(nil),              // 4: ai.SendMessageToAiReq
	(*SendMessageResp)(nil),                 // 5: ai.SendMessageResp
	(*GetChatHistoryMessagesFromAIReq)(nil), // 6: ai.GetChatHistoryMessagesFromAIReq
	(*GetChatUnreadMessagesFromAIReq)(nil),  // 7: ai.GetChatUnreadMessagesFromAIReq
	(*UpdateLastReadMsgRep)(nil),            // 8: ai.UpdateLastReadMsgRep
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: ai.SendMessageResp.CommonResponse:type_name -> ai.CommonResponse
	1, // 1: ai.ChatService.SetAgentInfo:input_type -> ai.SetAgentInfoReq
	2, // 2: ai.ChatService.GetAgentInfo:input_type -> ai.GetAgentInfoReq
	4, // 3: ai.ChatService.SendPrivateMessage:input_type -> ai.SendMessageToAiReq
	6, // 4: ai.ChatService.GetHistoryAiMessage:input_type -> ai.GetChatHistoryMessagesFromAIReq
	7, // 5: ai.ChatService.GetUnreadAiMessage:input_type -> ai.GetChatUnreadMessagesFromAIReq
	8, // 6: ai.ChatService.UpdateAiMsgLastRead:input_type -> ai.UpdateLastReadMsgRep
	0, // 7: ai.ChatService.SetAgentInfo:output_type -> ai.CommonResponse
	3, // 8: ai.ChatService.GetAgentInfo:output_type -> ai.GetAgentInfoResp
	5, // 9: ai.ChatService.SendPrivateMessage:output_type -> ai.SendMessageResp
	0, // 10: ai.ChatService.GetHistoryAiMessage:output_type -> ai.CommonResponse
	0, // 11: ai.ChatService.GetUnreadAiMessage:output_type -> ai.CommonResponse
	0, // 12: ai.ChatService.UpdateAiMsgLastRead:output_type -> ai.CommonResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
