// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_SetAgentInfo_FullMethodName        = "/ai.ChatService/SetAgentInfo"
	ChatService_GetAgentInfo_FullMethodName        = "/ai.ChatService/GetAgentInfo"
	ChatService_SendPrivateMessage_FullMethodName  = "/ai.ChatService/SendPrivateMessage"
	ChatService_GetHistoryAiMessage_FullMethodName = "/ai.ChatService/GetHistoryAiMessage"
	ChatService_GetUnreadAiMessage_FullMethodName  = "/ai.ChatService/GetUnreadAiMessage"
	ChatService_UpdateAiMsgLastRead_FullMethodName = "/ai.ChatService/UpdateAiMsgLastRead"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- 服务定义 ----------
type ChatServiceClient interface {
	// 自定义智能体
	SetAgentInfo(ctx context.Context, in *SetAgentInfoReq, opts ...grpc.CallOption) (*CommonResponse, error)
	// 获取智能体信息
	GetAgentInfo(ctx context.Context, in *GetAgentInfoReq, opts ...grpc.CallOption) (*GetAgentInfoResp, error)
	// 发送私聊消息
	SendPrivateMessage(ctx context.Context, in *SendMessageToAiReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// 拉取历史消息, WS推送
	GetHistoryAiMessage(ctx context.Context, in *GetChatHistoryMessagesFromAIReq, opts ...grpc.CallOption) (*CommonResponse, error)
	// 拉取新消息，WS推送
	GetUnreadAiMessage(ctx context.Context, in *GetChatUnreadMessagesFromAIReq, opts ...grpc.CallOption) (*CommonResponse, error)
	// 更新用户最后已读信息
	UpdateAiMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) SetAgentInfo(ctx context.Context, in *SetAgentInfoReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_SetAgentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetAgentInfo(ctx context.Context, in *GetAgentInfoReq, opts ...grpc.CallOption) (*GetAgentInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentInfoResp)
	err := c.cc.Invoke(ctx, ChatService_GetAgentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SendPrivateMessage(ctx context.Context, in *SendMessageToAiReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, ChatService_SendPrivateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetHistoryAiMessage(ctx context.Context, in *GetChatHistoryMessagesFromAIReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_GetHistoryAiMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetUnreadAiMessage(ctx context.Context, in *GetChatUnreadMessagesFromAIReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_GetUnreadAiMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UpdateAiMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_UpdateAiMsgLastRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// ---------- 服务定义 ----------
type ChatServiceServer interface {
	// 自定义智能体
	SetAgentInfo(context.Context, *SetAgentInfoReq) (*CommonResponse, error)
	// 获取智能体信息
	GetAgentInfo(context.Context, *GetAgentInfoReq) (*GetAgentInfoResp, error)
	// 发送私聊消息
	SendPrivateMessage(context.Context, *SendMessageToAiReq) (*SendMessageResp, error)
	// 拉取历史消息, WS推送
	GetHistoryAiMessage(context.Context, *GetChatHistoryMessagesFromAIReq) (*CommonResponse, error)
	// 拉取新消息，WS推送
	GetUnreadAiMessage(context.Context, *GetChatUnreadMessagesFromAIReq) (*CommonResponse, error)
	// 更新用户最后已读信息
	UpdateAiMsgLastRead(context.Context, *UpdateLastReadMsgRep) (*CommonResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) SetAgentInfo(context.Context, *SetAgentInfoReq) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAgentInfo not implemented")
}
func (UnimplementedChatServiceServer) GetAgentInfo(context.Context, *GetAgentInfoReq) (*GetAgentInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentInfo not implemented")
}
func (UnimplementedChatServiceServer) SendPrivateMessage(context.Context, *SendMessageToAiReq) (*SendMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPrivateMessage not implemented")
}
func (UnimplementedChatServiceServer) GetHistoryAiMessage(context.Context, *GetChatHistoryMessagesFromAIReq) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryAiMessage not implemented")
}
func (UnimplementedChatServiceServer) GetUnreadAiMessage(context.Context, *GetChatUnreadMessagesFromAIReq) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadAiMessage not implemented")
}
func (UnimplementedChatServiceServer) UpdateAiMsgLastRead(context.Context, *UpdateLastReadMsgRep) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAiMsgLastRead not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_SetAgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAgentInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetAgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetAgentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetAgentInfo(ctx, req.(*SetAgentInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetAgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetAgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetAgentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetAgentInfo(ctx, req.(*GetAgentInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendPrivateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageToAiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendPrivateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SendPrivateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendPrivateMessage(ctx, req.(*SendMessageToAiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetHistoryAiMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatHistoryMessagesFromAIReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetHistoryAiMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetHistoryAiMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetHistoryAiMessage(ctx, req.(*GetChatHistoryMessagesFromAIReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetUnreadAiMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatUnreadMessagesFromAIReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetUnreadAiMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetUnreadAiMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetUnreadAiMessage(ctx, req.(*GetChatUnreadMessagesFromAIReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpdateAiMsgLastRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLastReadMsgRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UpdateAiMsgLastRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UpdateAiMsgLastRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UpdateAiMsgLastRead(ctx, req.(*UpdateLastReadMsgRep))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetAgentInfo",
			Handler:    _ChatService_SetAgentInfo_Handler,
		},
		{
			MethodName: "GetAgentInfo",
			Handler:    _ChatService_GetAgentInfo_Handler,
		},
		{
			MethodName: "SendPrivateMessage",
			Handler:    _ChatService_SendPrivateMessage_Handler,
		},
		{
			MethodName: "GetHistoryAiMessage",
			Handler:    _ChatService_GetHistoryAiMessage_Handler,
		},
		{
			MethodName: "GetUnreadAiMessage",
			Handler:    _ChatService_GetUnreadAiMessage_Handler,
		},
		{
			MethodName: "UpdateAiMsgLastRead",
			Handler:    _ChatService_UpdateAiMsgLastRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
