// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userservice

import (
	"context"

	"IMM/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HeartReq           = user.HeartReq
	HeartResp          = user.HeartResp
	InfoUpdateReq      = user.InfoUpdateReq
	InfoUpdateResp     = user.InfoUpdateResp
	LoginReq           = user.LoginReq
	LoginResp          = user.LoginResp
	RegisterReq        = user.RegisterReq
	RegisterResp       = user.RegisterResp
	UpdateEmailReq     = user.UpdateEmailReq
	UpdateEmailResp    = user.UpdateEmailResp
	UpdatePasswordReq  = user.UpdatePasswordReq
	UpdatePasswordResp = user.UpdatePasswordResp
	UserInfoReq        = user.UserInfoReq
	UserInfoResp       = user.UserInfoResp

	UserService interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Heart(ctx context.Context, in *HeartReq, opts ...grpc.CallOption) (*HeartResp, error)
		GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
		UpdateUserInfo(ctx context.Context, in *InfoUpdateReq, opts ...grpc.CallOption) (*InfoUpdateResp, error)
		UpdateEmail(ctx context.Context, in *UpdateEmailReq, opts ...grpc.CallOption) (*UpdateEmailResp, error)
		UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) Heart(ctx context.Context, in *HeartReq, opts ...grpc.CallOption) (*HeartResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Heart(ctx, in, opts...)
}

func (m *defaultUserService) GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserInfo(ctx context.Context, in *InfoUpdateReq, opts ...grpc.CallOption) (*InfoUpdateResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) UpdateEmail(ctx context.Context, in *UpdateEmailReq, opts ...grpc.CallOption) (*UpdateEmailResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateEmail(ctx, in, opts...)
}

func (m *defaultUserService) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdatePassword(ctx, in, opts...)
}
