// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: relation.proto

package server

import (
	"context"

	"IMM/rpc/relation/internal/logic/groupmemberservice"
	"IMM/rpc/relation/internal/svc"
	"IMM/rpc/relation/relation"
)

type GroupMemberServiceServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedGroupMemberServiceServer
}

func NewGroupMemberServiceServer(svcCtx *svc.ServiceContext) *GroupMemberServiceServer {
	return &GroupMemberServiceServer{
		svcCtx: svcCtx,
	}
}

// ----- 群成员管理 -----
func (s *GroupMemberServiceServer) ApplyToJoinGroup(ctx context.Context, in *relation.ApplyToJoinGroupReq) (*relation.CommonResponse, error) {
	l := groupmemberservicelogic.NewApplyToJoinGroupLogic(ctx, s.svcCtx)
	return l.ApplyToJoinGroup(in)
}

func (s *GroupMemberServiceServer) ProcessGroupJoin(ctx context.Context, in *relation.ProcessGroupJoinReq) (*relation.CommonResponse, error) {
	l := groupmemberservicelogic.NewProcessGroupJoinLogic(ctx, s.svcCtx)
	return l.ProcessGroupJoin(in)
}

func (s *GroupMemberServiceServer) InviteToGroup(ctx context.Context, in *relation.InviteToGroupReq) (*relation.CommonResponse, error) {
	l := groupmemberservicelogic.NewInviteToGroupLogic(ctx, s.svcCtx)
	return l.InviteToGroup(in)
}

func (s *GroupMemberServiceServer) QuitGroup(ctx context.Context, in *relation.QuitGroupReq) (*relation.CommonResponse, error) {
	l := groupmemberservicelogic.NewQuitGroupLogic(ctx, s.svcCtx)
	return l.QuitGroup(in)
}

func (s *GroupMemberServiceServer) RemoveGroupMember(ctx context.Context, in *relation.RemoveGroupMemberReq) (*relation.CommonResponse, error) {
	l := groupmemberservicelogic.NewRemoveGroupMemberLogic(ctx, s.svcCtx)
	return l.RemoveGroupMember(in)
}

func (s *GroupMemberServiceServer) SetGroupMemberRole(ctx context.Context, in *relation.SetGroupMemberRoleReq) (*relation.CommonResponse, error) {
	l := groupmemberservicelogic.NewSetGroupMemberRoleLogic(ctx, s.svcCtx)
	return l.SetGroupMemberRole(in)
}

func (s *GroupMemberServiceServer) SetGroupNick(ctx context.Context, in *relation.SetGroupNickReq) (*relation.CommonResponse, error) {
	l := groupmemberservicelogic.NewSetGroupNickLogic(ctx, s.svcCtx)
	return l.SetGroupNick(in)
}

func (s *GroupMemberServiceServer) GetGroupMembers(ctx context.Context, in *relation.GetGroupMembersReq) (*relation.GetGroupMembersResp, error) {
	l := groupmemberservicelogic.NewGetGroupMembersLogic(ctx, s.svcCtx)
	return l.GetGroupMembers(in)
}

func (s *GroupMemberServiceServer) GetGroupJoinRequests(ctx context.Context, in *relation.GetGroupJoinRequestsReq) (*relation.GetGroupJoinRequestsResp, error) {
	l := groupmemberservicelogic.NewGetGroupJoinRequestsLogic(ctx, s.svcCtx)
	return l.GetGroupJoinRequests(in)
}
