// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aiservice

import (
	"context"

	"IMM/rpc/ai/ai"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CallLlmReq                      = ai.CallLlmReq
	CommonResponse                  = ai.CommonResponse
	GetAgentInfoReq                 = ai.GetAgentInfoReq
	GetAgentInfoResp                = ai.GetAgentInfoResp
	GetChatHistoryMessagesFromAIReq = ai.GetChatHistoryMessagesFromAIReq
	GetChatUnreadMessagesFromAIReq  = ai.GetChatUnreadMessagesFromAIReq
	GetSessionListReq               = ai.GetSessionListReq
	GetSessionListResp              = ai.GetSessionListResp
	PageInfo                        = ai.PageInfo
	PageRequest                     = ai.PageRequest
	SendMessageResp                 = ai.SendMessageResp
	SendMessageToAiReq              = ai.SendMessageToAiReq
	SessionInfo                     = ai.SessionInfo
	SetAgentInfoReq                 = ai.SetAgentInfoReq
	UpdateLastReadMsgRep            = ai.UpdateLastReadMsgRep

	AiService interface {
		// 自定义智能体
		SetAgentInfo(ctx context.Context, in *SetAgentInfoReq, opts ...grpc.CallOption) (*CommonResponse, error)
		// 获取智能体信息
		GetAgentInfo(ctx context.Context, in *GetAgentInfoReq, opts ...grpc.CallOption) (*GetAgentInfoResp, error)
		// 拉取会话列表
		GetSessionList(ctx context.Context, in *GetSessionListReq, opts ...grpc.CallOption) (*GetSessionListResp, error)
		// 构建 Ai 请求体
		ComposeAiMessage(ctx context.Context, in *SendMessageToAiReq, opts ...grpc.CallOption) (*SendMessageResp, error)
		// 调用 LLM 服务
		CallLlm(ctx context.Context, in *CallLlmReq, opts ...grpc.CallOption) (*CommonResponse, error)
		// 拉取历史消息, WS推送
		GetHistoryAiMessage(ctx context.Context, in *GetChatHistoryMessagesFromAIReq, opts ...grpc.CallOption) (*CommonResponse, error)
		// 拉取新消息，WS推送
		GetUnreadAiMessage(ctx context.Context, in *GetChatUnreadMessagesFromAIReq, opts ...grpc.CallOption) (*CommonResponse, error)
		// 更新用户最后已读信息
		UpdateAiMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error)
	}

	defaultAiService struct {
		cli zrpc.Client
	}
)

func NewAiService(cli zrpc.Client) AiService {
	return &defaultAiService{
		cli: cli,
	}
}

// 自定义智能体
func (m *defaultAiService) SetAgentInfo(ctx context.Context, in *SetAgentInfoReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := ai.NewAiServiceClient(m.cli.Conn())
	return client.SetAgentInfo(ctx, in, opts...)
}

// 获取智能体信息
func (m *defaultAiService) GetAgentInfo(ctx context.Context, in *GetAgentInfoReq, opts ...grpc.CallOption) (*GetAgentInfoResp, error) {
	client := ai.NewAiServiceClient(m.cli.Conn())
	return client.GetAgentInfo(ctx, in, opts...)
}

// 拉取会话列表
func (m *defaultAiService) GetSessionList(ctx context.Context, in *GetSessionListReq, opts ...grpc.CallOption) (*GetSessionListResp, error) {
	client := ai.NewAiServiceClient(m.cli.Conn())
	return client.GetSessionList(ctx, in, opts...)
}

// 构建 Ai 请求体
func (m *defaultAiService) ComposeAiMessage(ctx context.Context, in *SendMessageToAiReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := ai.NewAiServiceClient(m.cli.Conn())
	return client.ComposeAiMessage(ctx, in, opts...)
}

// 调用 LLM 服务
func (m *defaultAiService) CallLlm(ctx context.Context, in *CallLlmReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := ai.NewAiServiceClient(m.cli.Conn())
	return client.CallLlm(ctx, in, opts...)
}

// 拉取历史消息, WS推送
func (m *defaultAiService) GetHistoryAiMessage(ctx context.Context, in *GetChatHistoryMessagesFromAIReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := ai.NewAiServiceClient(m.cli.Conn())
	return client.GetHistoryAiMessage(ctx, in, opts...)
}

// 拉取新消息，WS推送
func (m *defaultAiService) GetUnreadAiMessage(ctx context.Context, in *GetChatUnreadMessagesFromAIReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := ai.NewAiServiceClient(m.cli.Conn())
	return client.GetUnreadAiMessage(ctx, in, opts...)
}

// 更新用户最后已读信息
func (m *defaultAiService) UpdateAiMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := ai.NewAiServiceClient(m.cli.Conn())
	return client.UpdateAiMsgLastRead(ctx, in, opts...)
}
