// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: relation.proto

package friendservice

import (
	"context"

	"IMM/rpc/relation/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResponse          = relation.CommonResponse
	DeleteFriendReq         = relation.DeleteFriendReq
	GetFriendListReq        = relation.GetFriendListReq
	GetFriendListResp       = relation.GetFriendListResp
	GetFriendRequestsReq    = relation.GetFriendRequestsReq
	GetFriendRequestsResp   = relation.GetFriendRequestsResp
	HandleFriendRequestReq  = relation.HandleFriendRequestReq
	HandleFriendRequestResp = relation.HandleFriendRequestResp
	SearchUserReq           = relation.SearchUserReq
	SearchUserResp          = relation.SearchUserResp
	SendFriendRequestReq    = relation.SendFriendRequestReq
	SendFriendRequestResp   = relation.SendFriendRequestResp
	SetFriendRemarkReq      = relation.SetFriendRemarkReq

	FriendService interface {
		// ----- 好友相关 -----
		SendFriendRequest(ctx context.Context, in *SendFriendRequestReq, opts ...grpc.CallOption) (*SendFriendRequestResp, error)
		HandleFriendRequest(ctx context.Context, in *HandleFriendRequestReq, opts ...grpc.CallOption) (*HandleFriendRequestResp, error)
		DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*CommonResponse, error)
		SetFriendRemark(ctx context.Context, in *SetFriendRemarkReq, opts ...grpc.CallOption) (*CommonResponse, error)
		GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error)
		GetFriendRequests(ctx context.Context, in *GetFriendRequestsReq, opts ...grpc.CallOption) (*GetFriendRequestsResp, error)
		SearchUser(ctx context.Context, in *SearchUserReq, opts ...grpc.CallOption) (*SearchUserResp, error)
	}

	defaultFriendService struct {
		cli zrpc.Client
	}
)

func NewFriendService(cli zrpc.Client) FriendService {
	return &defaultFriendService{
		cli: cli,
	}
}

// ----- 好友相关 -----
func (m *defaultFriendService) SendFriendRequest(ctx context.Context, in *SendFriendRequestReq, opts ...grpc.CallOption) (*SendFriendRequestResp, error) {
	client := relation.NewFriendServiceClient(m.cli.Conn())
	return client.SendFriendRequest(ctx, in, opts...)
}

func (m *defaultFriendService) HandleFriendRequest(ctx context.Context, in *HandleFriendRequestReq, opts ...grpc.CallOption) (*HandleFriendRequestResp, error) {
	client := relation.NewFriendServiceClient(m.cli.Conn())
	return client.HandleFriendRequest(ctx, in, opts...)
}

func (m *defaultFriendService) DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewFriendServiceClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}

func (m *defaultFriendService) SetFriendRemark(ctx context.Context, in *SetFriendRemarkReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewFriendServiceClient(m.cli.Conn())
	return client.SetFriendRemark(ctx, in, opts...)
}

func (m *defaultFriendService) GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error) {
	client := relation.NewFriendServiceClient(m.cli.Conn())
	return client.GetFriendList(ctx, in, opts...)
}

func (m *defaultFriendService) GetFriendRequests(ctx context.Context, in *GetFriendRequestsReq, opts ...grpc.CallOption) (*GetFriendRequestsResp, error) {
	client := relation.NewFriendServiceClient(m.cli.Conn())
	return client.GetFriendRequests(ctx, in, opts...)
}

func (m *defaultFriendService) SearchUser(ctx context.Context, in *SearchUserReq, opts ...grpc.CallOption) (*SearchUserResp, error) {
	client := relation.NewFriendServiceClient(m.cli.Conn())
	return client.SearchUser(ctx, in, opts...)
}
