syntax = "proto3";

package ai;

option go_package = "./ai";


// ---------- 通用消息结构 ----------
message CommonResponse {
    int32 code = 1;                  // 0 成功，非0错误码
    string msg = 2;                 // 返回消息
    bytes data = 3;
}

// ==================== 分页 ====================
message PageRequest {
  int32 page = 1;   // 页码，从1开始
  int32 size = 2;   // 每页数量
}

message PageInfo {
  int32 total = 1;
  int32 page = 2;
  int32 size = 3;
}

message SetAgentInfoReq{
    uint64 user_id = 1;
    uint64 agent_id = 2;
    string agent_name = 3;
    string agent_prompt = 4;
    string agent_avatar = 5;
}

message GetAgentInfoReq{
    uint64 user_id = 1;
    uint64 session_id = 2;
}

message GetAgentInfoResp{
    uint64 agent_id = 1;
    string agent_name = 2;
    string agent_prompt = 3;
    string agent_avatar = 4;
}

// 拉取会话列表
message GetSessionListReq{
    uint64 user_id = 1;
    PageRequest page = 2;
}

message SessionInfo{
    uint64 session_id = 1;
    uint64 agent_set = 2;
    int64 tokens = 3;
    uint64 last_msg = 4;
}

message GetSessionListResp{
    CommonResponse base = 1;
    repeated SessionInfo list = 2;   // 搜索到的会话列表记录
    PageInfo page = 3;
}


// 发送消息
message SendMessageToAiReq {
    uint64 user_id = 1;
    uint64 session_id = 2;
    int32 msg_type = 3;
    string content = 4;
    uint64 client_msg_id = 5;
}

// 发送消息响应
message SendMessageResp {
    uint64 msg_id = 1;
    int64 send_time = 2;
    CommonResponse CommonResponse = 3;
}

message CallLlmReq{
    uint64 user_id = 1;
    uint64 session_id = 2;
    bytes req = 3;
}

// ---------- 拉取历史对话（接收消息） ----------
// 拉取已读消息
message GetChatHistoryMessagesFromAIReq {
    uint64 user_id = 1;          // 当前用户ID（用于鉴权）
    uint64 session_id = 2;
    uint64 start_msg_id = 4;     // 起始消息ID 逆序往上
    int32 limit = 5;            // 每次拉取数量
}

// 拉取未读消息
message GetChatUnreadMessagesFromAIReq {
    uint64 user_id = 1;          // 当前用户ID（用于鉴权）
    uint64 session_id = 2;
    uint64 start_msg_id = 4;     // 起始消息ID，顺序往下
    int32 limit = 5;            // 每次拉取数量
}


message UpdateLastReadMsgRep {
    uint64 user_id = 1;
    uint64 session_id = 2;
    uint64 msg_id = 3;
}


// ---------- 服务定义 ----------
service AiService {
    // 自定义智能体
    rpc SetAgentInfo(SetAgentInfoReq) returns (CommonResponse);
    
    // 获取智能体信息
    rpc GetAgentInfo(GetAgentInfoReq) returns (GetAgentInfoResp);

    // 拉取会话列表
    rpc GetSessionList (GetSessionListReq) returns (GetSessionListResp);

    // 构建 Ai 请求体
    rpc ComposeAiMessage(SendMessageToAiReq) returns (SendMessageResp);

    // 调用 LLM 服务
    rpc CallLlm(CallLlmReq) returns (CommonResponse);

    // 拉取历史消息, WS推送
    rpc GetHistoryAiMessage (GetChatHistoryMessagesFromAIReq) returns (CommonResponse);

    // 拉取新消息，WS推送
    rpc GetUnreadAiMessage (GetChatUnreadMessagesFromAIReq) returns (CommonResponse);

    // 更新用户最后已读信息
    rpc UpdateAiMsgLastRead (UpdateLastReadMsgRep) returns (CommonResponse);


}