// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"IMM/rpc/ai/ai"
	"IMM/rpc/ai/internal/logic"
	"IMM/rpc/ai/internal/svc"
)

type AiServiceServer struct {
	svcCtx *svc.ServiceContext
	ai.UnimplementedAiServiceServer
}

func NewAiServiceServer(svcCtx *svc.ServiceContext) *AiServiceServer {
	return &AiServiceServer{
		svcCtx: svcCtx,
	}
}

// 自定义智能体
func (s *AiServiceServer) SetAgentInfo(ctx context.Context, in *ai.SetAgentInfoReq) (*ai.CommonResponse, error) {
	l := logic.NewSetAgentInfoLogic(ctx, s.svcCtx)
	return l.SetAgentInfo(in)
}

// 获取智能体信息
func (s *AiServiceServer) GetAgentInfo(ctx context.Context, in *ai.GetAgentInfoReq) (*ai.GetAgentInfoResp, error) {
	l := logic.NewGetAgentInfoLogic(ctx, s.svcCtx)
	return l.GetAgentInfo(in)
}

// 拉取会话列表
func (s *AiServiceServer) GetSessionList(ctx context.Context, in *ai.GetSessionListReq) (*ai.GetSessionListResp, error) {
	l := logic.NewGetSessionListLogic(ctx, s.svcCtx)
	return l.GetSessionList(in)
}

// 构建 Ai 请求体
func (s *AiServiceServer) ComposeAiMessage(ctx context.Context, in *ai.SendMessageToAiReq) (*ai.SendMessageResp, error) {
	l := logic.NewComposeAiMessageLogic(ctx, s.svcCtx)
	return l.ComposeAiMessage(in)
}

// 调用 LLM 服务
func (s *AiServiceServer) CallLlm(ctx context.Context, in *ai.CallLlmReq) (*ai.CommonResponse, error) {
	l := logic.NewCallLlmLogic(ctx, s.svcCtx)
	return l.CallLlm(in)
}

// 拉取历史消息, WS推送
func (s *AiServiceServer) GetHistoryAiMessage(ctx context.Context, in *ai.GetChatHistoryMessagesFromAIReq) (*ai.CommonResponse, error) {
	l := logic.NewGetHistoryAiMessageLogic(ctx, s.svcCtx)
	return l.GetHistoryAiMessage(in)
}

// 拉取新消息，WS推送
func (s *AiServiceServer) GetUnreadAiMessage(ctx context.Context, in *ai.GetChatUnreadMessagesFromAIReq) (*ai.CommonResponse, error) {
	l := logic.NewGetUnreadAiMessageLogic(ctx, s.svcCtx)
	return l.GetUnreadAiMessage(in)
}

// 更新用户最后已读信息
func (s *AiServiceServer) UpdateAiMsgLastRead(ctx context.Context, in *ai.UpdateLastReadMsgRep) (*ai.CommonResponse, error) {
	l := logic.NewUpdateAiMsgLastReadLogic(ctx, s.svcCtx)
	return l.UpdateAiMsgLastRead(in)
}
