// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"IMM/rpc/ai/ai"
	"IMM/rpc/ai/internal/logic"
	"IMM/rpc/ai/internal/svc"
)

type ChatServiceServer struct {
	svcCtx *svc.ServiceContext
	ai.UnimplementedChatServiceServer
}

func NewChatServiceServer(svcCtx *svc.ServiceContext) *ChatServiceServer {
	return &ChatServiceServer{
		svcCtx: svcCtx,
	}
}

// 自定义智能体
func (s *ChatServiceServer) SetAgentInfo(ctx context.Context, in *ai.SetAgentInfoReq) (*ai.CommonResponse, error) {
	l := logic.NewSetAgentInfoLogic(ctx, s.svcCtx)
	return l.SetAgentInfo(in)
}

// 获取智能体信息
func (s *ChatServiceServer) GetAgentInfo(ctx context.Context, in *ai.GetAgentInfoReq) (*ai.GetAgentInfoResp, error) {
	l := logic.NewGetAgentInfoLogic(ctx, s.svcCtx)
	return l.GetAgentInfo(in)
}

// 发送私聊消息
func (s *ChatServiceServer) SendPrivateMessage(ctx context.Context, in *ai.SendMessageToAiReq) (*ai.SendMessageResp, error) {
	l := logic.NewSendPrivateMessageLogic(ctx, s.svcCtx)
	return l.SendPrivateMessage(in)
}

// 拉取历史消息, WS推送
func (s *ChatServiceServer) GetHistoryAiMessage(ctx context.Context, in *ai.GetChatHistoryMessagesFromAIReq) (*ai.CommonResponse, error) {
	l := logic.NewGetHistoryAiMessageLogic(ctx, s.svcCtx)
	return l.GetHistoryAiMessage(in)
}

// 拉取新消息，WS推送
func (s *ChatServiceServer) GetUnreadAiMessage(ctx context.Context, in *ai.GetChatUnreadMessagesFromAIReq) (*ai.CommonResponse, error) {
	l := logic.NewGetUnreadAiMessageLogic(ctx, s.svcCtx)
	return l.GetUnreadAiMessage(in)
}

// 更新用户最后已读信息
func (s *ChatServiceServer) UpdateAiMsgLastRead(ctx context.Context, in *ai.UpdateLastReadMsgRep) (*ai.CommonResponse, error) {
	l := logic.NewUpdateAiMsgLastReadLogic(ctx, s.svcCtx)
	return l.UpdateAiMsgLastRead(in)
}
