// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: relation.proto

package server

import (
	"context"

	"IMM/rpc/relation/internal/logic/groupservice"
	"IMM/rpc/relation/internal/svc"
	"IMM/rpc/relation/relation"
)

type GroupServiceServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedGroupServiceServer
}

func NewGroupServiceServer(svcCtx *svc.ServiceContext) *GroupServiceServer {
	return &GroupServiceServer{
		svcCtx: svcCtx,
	}
}

// ----- 群组管理 -----
func (s *GroupServiceServer) CreateGroup(ctx context.Context, in *relation.CreateGroupReq) (*relation.CreateGroupResp, error) {
	l := groupservicelogic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *GroupServiceServer) UpdateGroupInfo(ctx context.Context, in *relation.UpdateGroupInfoReq) (*relation.CommonResponse, error) {
	l := groupservicelogic.NewUpdateGroupInfoLogic(ctx, s.svcCtx)
	return l.UpdateGroupInfo(in)
}

func (s *GroupServiceServer) DismissGroup(ctx context.Context, in *relation.DismissGroupReq) (*relation.CommonResponse, error) {
	l := groupservicelogic.NewDismissGroupLogic(ctx, s.svcCtx)
	return l.DismissGroup(in)
}

func (s *GroupServiceServer) GetGroupInfo(ctx context.Context, in *relation.GetGroupInfoReq) (*relation.GetGroupInfoResp, error) {
	l := groupservicelogic.NewGetGroupInfoLogic(ctx, s.svcCtx)
	return l.GetGroupInfo(in)
}
