// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: chat.proto

package chatservice

import (
	"context"

	"IMM/rpc/chat/chat"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResponse               = chat.CommonResponse
	GetChatHistoryMessagesReq    = chat.GetChatHistoryMessagesReq
	GetChatNewMessagesNumberReq  = chat.GetChatNewMessagesNumberReq
	GetChatUnreadMessagesReq     = chat.GetChatUnreadMessagesReq
	GetGroupHistoryMessagesReq   = chat.GetGroupHistoryMessagesReq
	GetGroupNewMessagesNumberReq = chat.GetGroupNewMessagesNumberReq
	GetGroupUnreadMessagesReq    = chat.GetGroupUnreadMessagesReq
	GetMessageNumberResp         = chat.GetMessageNumberResp
	SendGroupMessageReq          = chat.SendGroupMessageReq
	SendMessageResp              = chat.SendMessageResp
	SendPrivateMessageReq        = chat.SendPrivateMessageReq
	Unread                       = chat.Unread
	UpdateLastReadMsgRep         = chat.UpdateLastReadMsgRep

	ChatService interface {
		// 发送私聊消息
		SendPrivateMessage(ctx context.Context, in *SendPrivateMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
		// 发送群聊消息
		SendGroupMessage(ctx context.Context, in *SendGroupMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
		// 拉取历史消息
		GetHistoryChatMessage(ctx context.Context, in *GetChatHistoryMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error)
		GetHistoryGroupMessages(ctx context.Context, in *GetGroupHistoryMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error)
		// 拉取新消息
		GetUnreadChatMessage(ctx context.Context, in *GetChatUnreadMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error)
		GetUnreadGroupMessages(ctx context.Context, in *GetGroupUnreadMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error)
		// 获取新消息数量
		GetNewChatMessageNumber(ctx context.Context, in *GetChatNewMessagesNumberReq, opts ...grpc.CallOption) (*GetMessageNumberResp, error)
		GetNewGroupMessageNumber(ctx context.Context, in *GetGroupNewMessagesNumberReq, opts ...grpc.CallOption) (*GetMessageNumberResp, error)
		// 更新用户最后已读信息
		UpdateChatMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error)
		UpdataGroupMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error)
	}

	defaultChatService struct {
		cli zrpc.Client
	}
)

func NewChatService(cli zrpc.Client) ChatService {
	return &defaultChatService{
		cli: cli,
	}
}

// 发送私聊消息
func (m *defaultChatService) SendPrivateMessage(ctx context.Context, in *SendPrivateMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.SendPrivateMessage(ctx, in, opts...)
}

// 发送群聊消息
func (m *defaultChatService) SendGroupMessage(ctx context.Context, in *SendGroupMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.SendGroupMessage(ctx, in, opts...)
}

// 拉取历史消息
func (m *defaultChatService) GetHistoryChatMessage(ctx context.Context, in *GetChatHistoryMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.GetHistoryChatMessage(ctx, in, opts...)
}

func (m *defaultChatService) GetHistoryGroupMessages(ctx context.Context, in *GetGroupHistoryMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.GetHistoryGroupMessages(ctx, in, opts...)
}

// 拉取新消息
func (m *defaultChatService) GetUnreadChatMessage(ctx context.Context, in *GetChatUnreadMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.GetUnreadChatMessage(ctx, in, opts...)
}

func (m *defaultChatService) GetUnreadGroupMessages(ctx context.Context, in *GetGroupUnreadMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.GetUnreadGroupMessages(ctx, in, opts...)
}

// 获取新消息数量
func (m *defaultChatService) GetNewChatMessageNumber(ctx context.Context, in *GetChatNewMessagesNumberReq, opts ...grpc.CallOption) (*GetMessageNumberResp, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.GetNewChatMessageNumber(ctx, in, opts...)
}

func (m *defaultChatService) GetNewGroupMessageNumber(ctx context.Context, in *GetGroupNewMessagesNumberReq, opts ...grpc.CallOption) (*GetMessageNumberResp, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.GetNewGroupMessageNumber(ctx, in, opts...)
}

// 更新用户最后已读信息
func (m *defaultChatService) UpdateChatMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.UpdateChatMsgLastRead(ctx, in, opts...)
}

func (m *defaultChatService) UpdataGroupMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.UpdataGroupMsgLastRead(ctx, in, opts...)
}
