// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommonResp struct {
	Code int32  `json:"code"` // 0成功，非0错误码
	Msg  string `json:"msg"`
}

type DeleteFriendReq struct {
	FriendId uint64 `json:"friend_id,string"`
}

type FriendInfo struct {
	Id          uint64 `json:"id,string"`
	FriendName  string `json:"friend_name"`
	Remark      string `json:"remark"`
	Avatar      string `json:"avatar"`
	Signature   string `json:"signature"`
	Gender      string `json:"gender"`
	Birthday    int64  `json:"birthday"`
	LastOnline  int64  `json:"last_online"`
	OnlineStatu bool   `json:"online_statu"`
	Status      int32  `json:"status"`
	CreatedAt   int64  `json:"created_at"`
}

type GetFriendApplyReq struct {
	PageReq
}

type GetFriendApplyResp struct {
	CommonResp
	List []FriendInfo `json:"list"`
	PageResp
}

type GetFriendListReq struct {
	PageReq
}

type GetFriendListResp struct {
	CommonResp
	List []FriendInfo `json:"list"`
	PageResp
}

type GetUnreadNumberResp struct {
	List []UnReadInfo `json:"list"`
}

type HandleFriendReq struct {
	RequestId uint64 `json:"request_id,string"`
	Accept    bool   `json:"accept"`
	SenderId  uint64 `json:"sender_id,string"`
	HandlerID uint64 `json:"user_id,string"`
}

type HeartRequest struct {
	Uid          uint64 `json:"uid,string"`
	RefreshToken string `json:"refresh_token"`
	DeviceId     string `json:"device_id"`
	Platform     string `json:"platform"`
}

type HeartResponse struct {
	Code        int    `json:"code"`
	AccessToken string `json:"access_token"`
}

type LoginRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	Platform string `json:"platform"`
	DeviceId string `json:"device_id"`
}

type LoginResponse struct {
	Code         int    `json:"code"`
	Uid          uint64 `json:"uid,string"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	Msg          string `json:"message"`
}

type PageReq struct {
	Page int32 `form:"page,default=1"`
	Size int32 `form:"size,default=20"`
}

type PageResp struct {
	Total int32 `json:"total"`
	Page  int32 `json:"page"`
	Size  int32 `json:"size"`
}

type RegisterRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"message"`
}

type SearchUserReq struct {
	SearchName string `form:"search_name"`
	PageReq
}

type SearchUserResp struct {
	CommonResp
	List []FriendInfo `json:"list"`
	PageResp
}

type SendFriendReq struct {
	FriendId uint64 `json:"friend_id,string"`
	Msg      string `json:"msg"`
}

type SendFriendResp struct {
	CommonResp
	RequestId uint64 `json:"request_id,string"`
}

type SetRemarkReq struct {
	FriendId uint64 `json:"friend_id,string"`
	Remark   string `json:"remark"`
}

type UnReadInfo struct {
	Id    uint64 `json:"id,string"`
	Count int    `json:"count"`
}

type UpdateAvatarResponse struct {
	Code        int    `json:"code"`
	PhotoFileID string `json:"photo_id"`
}

type UpdateEmailRequest struct {
	Account string `json:"account"`
	Email   string `json:"email"`
}

type UpdateEmailResponse struct {
	Code int `json:"code"`
}

type UpdatePasswordRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type UpdatePasswordResponse struct {
	Code int `json:"code"`
}

type UpdateUserInfoRequest struct {
	Name      string `json:"name"`
	Photo     string `json:"photo"`
	Gender    string `json:"gender"`
	Birthday  int64  `json:"birthday"`
	Signature string `json:"signature"`
}

type UpdateUserInfoResponse struct {
	Code int `json:"code"`
}

type UserInfoRequest struct {
	Account string `form:"account"`
}

type UserInfoResponse struct {
	Name       string `json:"name"`
	Photo      string `json:"photo"`
	Gender     string `json:"gender"`
	Signature  string `json:"signature"`
	Birthday   int64  `json:"birthday"`
	CreatedAt  int64  `json:"createdtime"`
	LastOnline int64  `json:"lastonline"`
	Online     bool   `json:"online"`
}
