// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: relation.proto

package server

import (
	"context"

	"IMM/rpc/relation/internal/logic/friendservice"
	"IMM/rpc/relation/internal/svc"
	"IMM/rpc/relation/relation"
)

type FriendServiceServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedFriendServiceServer
}

func NewFriendServiceServer(svcCtx *svc.ServiceContext) *FriendServiceServer {
	return &FriendServiceServer{
		svcCtx: svcCtx,
	}
}

// ----- 好友相关 -----
func (s *FriendServiceServer) SendFriendRequest(ctx context.Context, in *relation.SendFriendRequestReq) (*relation.SendFriendRequestResp, error) {
	l := friendservicelogic.NewSendFriendRequestLogic(ctx, s.svcCtx)
	return l.SendFriendRequest(in)
}

func (s *FriendServiceServer) HandleFriendRequest(ctx context.Context, in *relation.HandleFriendRequestReq) (*relation.HandleFriendRequestResp, error) {
	l := friendservicelogic.NewHandleFriendRequestLogic(ctx, s.svcCtx)
	return l.HandleFriendRequest(in)
}

func (s *FriendServiceServer) DeleteFriend(ctx context.Context, in *relation.DeleteFriendReq) (*relation.CommonResponse, error) {
	l := friendservicelogic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

func (s *FriendServiceServer) SetFriendRemark(ctx context.Context, in *relation.SetFriendRemarkReq) (*relation.CommonResponse, error) {
	l := friendservicelogic.NewSetFriendRemarkLogic(ctx, s.svcCtx)
	return l.SetFriendRemark(in)
}

func (s *FriendServiceServer) GetFriendList(ctx context.Context, in *relation.GetFriendListReq) (*relation.GetFriendListResp, error) {
	l := friendservicelogic.NewGetFriendListLogic(ctx, s.svcCtx)
	return l.GetFriendList(in)
}

func (s *FriendServiceServer) GetFriendRequests(ctx context.Context, in *relation.GetFriendRequestsReq) (*relation.GetFriendRequestsResp, error) {
	l := friendservicelogic.NewGetFriendRequestsLogic(ctx, s.svcCtx)
	return l.GetFriendRequests(in)
}

func (s *FriendServiceServer) SearchUser(ctx context.Context, in *relation.SearchUserReq) (*relation.SearchUserResp, error) {
	l := friendservicelogic.NewSearchUserLogic(ctx, s.svcCtx)
	return l.SearchUser(in)
}
