// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: relation.proto

package groupservice

import (
	"context"

	"IMM/rpc/relation/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResponse     = relation.CommonResponse
	CreateGroupReq     = relation.CreateGroupReq
	CreateGroupResp    = relation.CreateGroupResp
	DismissGroupReq    = relation.DismissGroupReq
	GetGroupInfoReq    = relation.GetGroupInfoReq
	GetGroupInfoResp   = relation.GetGroupInfoResp
	UpdateGroupInfoReq = relation.UpdateGroupInfoReq

	GroupService interface {
		// ----- 群组管理 -----
		CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
		UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoReq, opts ...grpc.CallOption) (*CommonResponse, error)
		DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...grpc.CallOption) (*CommonResponse, error)
		GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
	}

	defaultGroupService struct {
		cli zrpc.Client
	}
)

func NewGroupService(cli zrpc.Client) GroupService {
	return &defaultGroupService{
		cli: cli,
	}
}

// ----- 群组管理 -----
func (m *defaultGroupService) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	client := relation.NewGroupServiceClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

func (m *defaultGroupService) UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewGroupServiceClient(m.cli.Conn())
	return client.UpdateGroupInfo(ctx, in, opts...)
}

func (m *defaultGroupService) DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := relation.NewGroupServiceClient(m.cli.Conn())
	return client.DismissGroup(ctx, in, opts...)
}

func (m *defaultGroupService) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	client := relation.NewGroupServiceClient(m.cli.Conn())
	return client.GetGroupInfo(ctx, in, opts...)
}
