// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_SendPrivateMessage_FullMethodName       = "/chat.ChatService/SendPrivateMessage"
	ChatService_SendGroupMessage_FullMethodName         = "/chat.ChatService/SendGroupMessage"
	ChatService_GetHistoryChatMessage_FullMethodName    = "/chat.ChatService/GetHistoryChatMessage"
	ChatService_GetHistoryGroupMessages_FullMethodName  = "/chat.ChatService/GetHistoryGroupMessages"
	ChatService_GetUnreadChatMessage_FullMethodName     = "/chat.ChatService/GetUnreadChatMessage"
	ChatService_GetUnreadGroupMessages_FullMethodName   = "/chat.ChatService/GetUnreadGroupMessages"
	ChatService_GetNewChatMessageNumber_FullMethodName  = "/chat.ChatService/GetNewChatMessageNumber"
	ChatService_GetNewGroupMessageNumber_FullMethodName = "/chat.ChatService/GetNewGroupMessageNumber"
	ChatService_UpdateChatMsgLastRead_FullMethodName    = "/chat.ChatService/UpdateChatMsgLastRead"
	ChatService_UpdataGroupMsgLastRead_FullMethodName   = "/chat.ChatService/UpdataGroupMsgLastRead"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- 服务定义 ----------
type ChatServiceClient interface {
	// 发送私聊消息
	SendPrivateMessage(ctx context.Context, in *SendPrivateMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// 发送群聊消息
	SendGroupMessage(ctx context.Context, in *SendGroupMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// 拉取历史消息
	GetHistoryChatMessage(ctx context.Context, in *GetChatHistoryMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error)
	GetHistoryGroupMessages(ctx context.Context, in *GetGroupHistoryMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error)
	// 拉取新消息
	GetUnreadChatMessage(ctx context.Context, in *GetChatUnreadMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error)
	GetUnreadGroupMessages(ctx context.Context, in *GetGroupUnreadMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error)
	// 获取新消息数量
	GetNewChatMessageNumber(ctx context.Context, in *GetChatNewMessagesNumberReq, opts ...grpc.CallOption) (*GetMessageNumberResp, error)
	GetNewGroupMessageNumber(ctx context.Context, in *GetGroupNewMessagesNumberReq, opts ...grpc.CallOption) (*GetMessageNumberResp, error)
	// 更新用户最后已读信息
	UpdateChatMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error)
	UpdataGroupMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) SendPrivateMessage(ctx context.Context, in *SendPrivateMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, ChatService_SendPrivateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SendGroupMessage(ctx context.Context, in *SendGroupMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, ChatService_SendGroupMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetHistoryChatMessage(ctx context.Context, in *GetChatHistoryMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_GetHistoryChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetHistoryGroupMessages(ctx context.Context, in *GetGroupHistoryMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_GetHistoryGroupMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetUnreadChatMessage(ctx context.Context, in *GetChatUnreadMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_GetUnreadChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetUnreadGroupMessages(ctx context.Context, in *GetGroupUnreadMessagesReq, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_GetUnreadGroupMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetNewChatMessageNumber(ctx context.Context, in *GetChatNewMessagesNumberReq, opts ...grpc.CallOption) (*GetMessageNumberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageNumberResp)
	err := c.cc.Invoke(ctx, ChatService_GetNewChatMessageNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetNewGroupMessageNumber(ctx context.Context, in *GetGroupNewMessagesNumberReq, opts ...grpc.CallOption) (*GetMessageNumberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageNumberResp)
	err := c.cc.Invoke(ctx, ChatService_GetNewGroupMessageNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UpdateChatMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_UpdateChatMsgLastRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UpdataGroupMsgLastRead(ctx context.Context, in *UpdateLastReadMsgRep, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ChatService_UpdataGroupMsgLastRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// ---------- 服务定义 ----------
type ChatServiceServer interface {
	// 发送私聊消息
	SendPrivateMessage(context.Context, *SendPrivateMessageReq) (*SendMessageResp, error)
	// 发送群聊消息
	SendGroupMessage(context.Context, *SendGroupMessageReq) (*SendMessageResp, error)
	// 拉取历史消息
	GetHistoryChatMessage(context.Context, *GetChatHistoryMessagesReq) (*CommonResponse, error)
	GetHistoryGroupMessages(context.Context, *GetGroupHistoryMessagesReq) (*CommonResponse, error)
	// 拉取新消息
	GetUnreadChatMessage(context.Context, *GetChatUnreadMessagesReq) (*CommonResponse, error)
	GetUnreadGroupMessages(context.Context, *GetGroupUnreadMessagesReq) (*CommonResponse, error)
	// 获取新消息数量
	GetNewChatMessageNumber(context.Context, *GetChatNewMessagesNumberReq) (*GetMessageNumberResp, error)
	GetNewGroupMessageNumber(context.Context, *GetGroupNewMessagesNumberReq) (*GetMessageNumberResp, error)
	// 更新用户最后已读信息
	UpdateChatMsgLastRead(context.Context, *UpdateLastReadMsgRep) (*CommonResponse, error)
	UpdataGroupMsgLastRead(context.Context, *UpdateLastReadMsgRep) (*CommonResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) SendPrivateMessage(context.Context, *SendPrivateMessageReq) (*SendMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPrivateMessage not implemented")
}
func (UnimplementedChatServiceServer) SendGroupMessage(context.Context, *SendGroupMessageReq) (*SendMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGroupMessage not implemented")
}
func (UnimplementedChatServiceServer) GetHistoryChatMessage(context.Context, *GetChatHistoryMessagesReq) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryChatMessage not implemented")
}
func (UnimplementedChatServiceServer) GetHistoryGroupMessages(context.Context, *GetGroupHistoryMessagesReq) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryGroupMessages not implemented")
}
func (UnimplementedChatServiceServer) GetUnreadChatMessage(context.Context, *GetChatUnreadMessagesReq) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadChatMessage not implemented")
}
func (UnimplementedChatServiceServer) GetUnreadGroupMessages(context.Context, *GetGroupUnreadMessagesReq) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadGroupMessages not implemented")
}
func (UnimplementedChatServiceServer) GetNewChatMessageNumber(context.Context, *GetChatNewMessagesNumberReq) (*GetMessageNumberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewChatMessageNumber not implemented")
}
func (UnimplementedChatServiceServer) GetNewGroupMessageNumber(context.Context, *GetGroupNewMessagesNumberReq) (*GetMessageNumberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewGroupMessageNumber not implemented")
}
func (UnimplementedChatServiceServer) UpdateChatMsgLastRead(context.Context, *UpdateLastReadMsgRep) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChatMsgLastRead not implemented")
}
func (UnimplementedChatServiceServer) UpdataGroupMsgLastRead(context.Context, *UpdateLastReadMsgRep) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdataGroupMsgLastRead not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_SendPrivateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPrivateMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendPrivateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SendPrivateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendPrivateMessage(ctx, req.(*SendPrivateMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendGroupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendGroupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SendGroupMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendGroupMessage(ctx, req.(*SendGroupMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetHistoryChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatHistoryMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetHistoryChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetHistoryChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetHistoryChatMessage(ctx, req.(*GetChatHistoryMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetHistoryGroupMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupHistoryMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetHistoryGroupMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetHistoryGroupMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetHistoryGroupMessages(ctx, req.(*GetGroupHistoryMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetUnreadChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatUnreadMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetUnreadChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetUnreadChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetUnreadChatMessage(ctx, req.(*GetChatUnreadMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetUnreadGroupMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupUnreadMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetUnreadGroupMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetUnreadGroupMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetUnreadGroupMessages(ctx, req.(*GetGroupUnreadMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetNewChatMessageNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatNewMessagesNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetNewChatMessageNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetNewChatMessageNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetNewChatMessageNumber(ctx, req.(*GetChatNewMessagesNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetNewGroupMessageNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupNewMessagesNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetNewGroupMessageNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetNewGroupMessageNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetNewGroupMessageNumber(ctx, req.(*GetGroupNewMessagesNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpdateChatMsgLastRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLastReadMsgRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UpdateChatMsgLastRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UpdateChatMsgLastRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UpdateChatMsgLastRead(ctx, req.(*UpdateLastReadMsgRep))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpdataGroupMsgLastRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLastReadMsgRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UpdataGroupMsgLastRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UpdataGroupMsgLastRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UpdataGroupMsgLastRead(ctx, req.(*UpdateLastReadMsgRep))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPrivateMessage",
			Handler:    _ChatService_SendPrivateMessage_Handler,
		},
		{
			MethodName: "SendGroupMessage",
			Handler:    _ChatService_SendGroupMessage_Handler,
		},
		{
			MethodName: "GetHistoryChatMessage",
			Handler:    _ChatService_GetHistoryChatMessage_Handler,
		},
		{
			MethodName: "GetHistoryGroupMessages",
			Handler:    _ChatService_GetHistoryGroupMessages_Handler,
		},
		{
			MethodName: "GetUnreadChatMessage",
			Handler:    _ChatService_GetUnreadChatMessage_Handler,
		},
		{
			MethodName: "GetUnreadGroupMessages",
			Handler:    _ChatService_GetUnreadGroupMessages_Handler,
		},
		{
			MethodName: "GetNewChatMessageNumber",
			Handler:    _ChatService_GetNewChatMessageNumber_Handler,
		},
		{
			MethodName: "GetNewGroupMessageNumber",
			Handler:    _ChatService_GetNewGroupMessageNumber_Handler,
		},
		{
			MethodName: "UpdateChatMsgLastRead",
			Handler:    _ChatService_UpdateChatMsgLastRead_Handler,
		},
		{
			MethodName: "UpdataGroupMsgLastRead",
			Handler:    _ChatService_UpdataGroupMsgLastRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
