// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // http
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`  // 返回消息, 由GateWay进行封装推送
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 发送私聊消息
type SendPrivateMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    uint64                 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      uint64                 `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId   uint64                 `protobuf:"varint,5,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateMessageReq) Reset() {
	*x = SendPrivateMessageReq{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateMessageReq) ProtoMessage() {}

func (x *SendPrivateMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateMessageReq.ProtoReflect.Descriptor instead.
func (*SendPrivateMessageReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendPrivateMessageReq) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *SendPrivateMessageReq) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *SendPrivateMessageReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SendPrivateMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendPrivateMessageReq) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

// 发送群聊消息
type SendGroupMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    uint64                 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId   uint64                 `protobuf:"varint,5,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端标识的唯一消息id， 用于防重发
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageReq) Reset() {
	*x = SendGroupMessageReq{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageReq) ProtoMessage() {}

func (x *SendGroupMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageReq.ProtoReflect.Descriptor instead.
func (*SendGroupMessageReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendGroupMessageReq) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *SendGroupMessageReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SendGroupMessageReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SendGroupMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendGroupMessageReq) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

// 发送群聊消息响应
type SendMessageResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          uint64                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SendTime       int64                  `protobuf:"varint,2,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	CommonResponse *CommonResponse        `protobuf:"bytes,3,opt,name=CommonResponse,proto3" json:"CommonResponse,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResp) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendMessageResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *SendMessageResp) GetCommonResponse() *CommonResponse {
	if x != nil {
		return x.CommonResponse
	}
	return nil
}

// ---------- 拉取历史消息（接收消息） ----------
// 拉取已读消息
type GetChatHistoryMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 当前用户ID（用于鉴权）
	FromUserId    uint64                 `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 对方用户ID
	StartMsgId    uint64                 `protobuf:"varint,4,opt,name=start_msg_id,json=startMsgId,proto3" json:"start_msg_id,omitempty"` // 起始消息ID 逆序往上
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                               // 每次拉取数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryMessagesReq) Reset() {
	*x = GetChatHistoryMessagesReq{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryMessagesReq) ProtoMessage() {}

func (x *GetChatHistoryMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryMessagesReq.ProtoReflect.Descriptor instead.
func (*GetChatHistoryMessagesReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatHistoryMessagesReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetChatHistoryMessagesReq) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *GetChatHistoryMessagesReq) GetStartMsgId() uint64 {
	if x != nil {
		return x.StartMsgId
	}
	return 0
}

func (x *GetChatHistoryMessagesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGroupHistoryMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 当前用户ID（用于鉴权）判断是否组成员
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`            // 群组ID
	StartMsgId    uint64                 `protobuf:"varint,4,opt,name=start_msg_id,json=startMsgId,proto3" json:"start_msg_id,omitempty"` // 起始消息ID
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                               // 拉取数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupHistoryMessagesReq) Reset() {
	*x = GetGroupHistoryMessagesReq{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupHistoryMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupHistoryMessagesReq) ProtoMessage() {}

func (x *GetGroupHistoryMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupHistoryMessagesReq.ProtoReflect.Descriptor instead.
func (*GetGroupHistoryMessagesReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetGroupHistoryMessagesReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGroupHistoryMessagesReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupHistoryMessagesReq) GetStartMsgId() uint64 {
	if x != nil {
		return x.StartMsgId
	}
	return 0
}

func (x *GetGroupHistoryMessagesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 拉取未读消息
type GetChatUnreadMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 当前用户ID（用于鉴权）
	FromUserId    uint64                 `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 对方用户ID
	StartMsgId    uint64                 `protobuf:"varint,4,opt,name=start_msg_id,json=startMsgId,proto3" json:"start_msg_id,omitempty"` // 起始消息ID，顺序往下
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                               // 每次拉取数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatUnreadMessagesReq) Reset() {
	*x = GetChatUnreadMessagesReq{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatUnreadMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatUnreadMessagesReq) ProtoMessage() {}

func (x *GetChatUnreadMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatUnreadMessagesReq.ProtoReflect.Descriptor instead.
func (*GetChatUnreadMessagesReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatUnreadMessagesReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetChatUnreadMessagesReq) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *GetChatUnreadMessagesReq) GetStartMsgId() uint64 {
	if x != nil {
		return x.StartMsgId
	}
	return 0
}

func (x *GetChatUnreadMessagesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGroupUnreadMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 当前用户ID（用于鉴权）判断是否组成员
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`            // 群组ID
	StartMsgId    uint64                 `protobuf:"varint,4,opt,name=start_msg_id,json=startMsgId,proto3" json:"start_msg_id,omitempty"` // 起始消息ID
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                               // 拉取数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupUnreadMessagesReq) Reset() {
	*x = GetGroupUnreadMessagesReq{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupUnreadMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupUnreadMessagesReq) ProtoMessage() {}

func (x *GetGroupUnreadMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupUnreadMessagesReq.ProtoReflect.Descriptor instead.
func (*GetGroupUnreadMessagesReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetGroupUnreadMessagesReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGroupUnreadMessagesReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupUnreadMessagesReq) GetStartMsgId() uint64 {
	if x != nil {
		return x.StartMsgId
	}
	return 0
}

func (x *GetGroupUnreadMessagesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ---------- 获取新消息数量 ----------
type GetChatNewMessagesNumberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前用户ID（用于鉴权）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatNewMessagesNumberReq) Reset() {
	*x = GetChatNewMessagesNumberReq{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatNewMessagesNumberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatNewMessagesNumberReq) ProtoMessage() {}

func (x *GetChatNewMessagesNumberReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatNewMessagesNumberReq.ProtoReflect.Descriptor instead.
func (*GetChatNewMessagesNumberReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatNewMessagesNumberReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetGroupNewMessagesNumberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前用户ID（用于鉴权）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupNewMessagesNumberReq) Reset() {
	*x = GetGroupNewMessagesNumberReq{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupNewMessagesNumberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupNewMessagesNumberReq) ProtoMessage() {}

func (x *GetGroupNewMessagesNumberReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupNewMessagesNumberReq.ProtoReflect.Descriptor instead.
func (*GetGroupNewMessagesNumberReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetGroupNewMessagesNumberReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Unread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unread) Reset() {
	*x = Unread{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unread) ProtoMessage() {}

func (x *Unread) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unread.ProtoReflect.Descriptor instead.
func (*Unread) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *Unread) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Unread) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetMessageNumberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	List          []*Unread              `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageNumberResp) Reset() {
	*x = GetMessageNumberResp{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageNumberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageNumberResp) ProtoMessage() {}

func (x *GetMessageNumberResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageNumberResp.ProtoReflect.Descriptor instead.
func (*GetMessageNumberResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *GetMessageNumberResp) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMessageNumberResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetMessageNumberResp) GetList() []*Unread {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateLastReadMsgRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	MsgId         uint64                 `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastReadMsgRep) Reset() {
	*x = UpdateLastReadMsgRep{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastReadMsgRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastReadMsgRep) ProtoMessage() {}

func (x *UpdateLastReadMsgRep) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastReadMsgRep.ProtoReflect.Descriptor instead.
func (*UpdateLastReadMsgRep) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateLastReadMsgRep) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateLastReadMsgRep) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *UpdateLastReadMsgRep) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x04chat\"8\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xb0\x01\n" +
	"\x15SendPrivateMessageReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x04R\btoUserId\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x05 \x01(\x04R\vclientMsgId\"\xab\x01\n" +
	"\x13SendGroupMessageReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x04R\n" +
	"fromUserId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x05 \x01(\x04R\vclientMsgId\"\x83\x01\n" +
	"\x0fSendMessageResp\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x04R\x05msgId\x12\x1b\n" +
	"\tsend_time\x18\x02 \x01(\x03R\bsendTime\x12<\n" +
	"\x0eCommonResponse\x18\x03 \x01(\v2\x14.chat.CommonResponseR\x0eCommonResponse\"\x8e\x01\n" +
	"\x19GetChatHistoryMessagesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x04R\n" +
	"fromUserId\x12 \n" +
	"\fstart_msg_id\x18\x04 \x01(\x04R\n" +
	"startMsgId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x88\x01\n" +
	"\x1aGetGroupHistoryMessagesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12 \n" +
	"\fstart_msg_id\x18\x04 \x01(\x04R\n" +
	"startMsgId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x8d\x01\n" +
	"\x18GetChatUnreadMessagesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x04R\n" +
	"fromUserId\x12 \n" +
	"\fstart_msg_id\x18\x04 \x01(\x04R\n" +
	"startMsgId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x87\x01\n" +
	"\x19GetGroupUnreadMessagesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12 \n" +
	"\fstart_msg_id\x18\x04 \x01(\x04R\n" +
	"startMsgId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"6\n" +
	"\x1bGetChatNewMessagesNumberReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"7\n" +
	"\x1cGetGroupNewMessagesNumberReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\".\n" +
	"\x06unread\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"b\n" +
	"\x14GetMessageNumberResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12 \n" +
	"\x04list\x18\x03 \x03(\v2\f.chat.unreadR\x04list\"c\n" +
	"\x14UpdateLastReadMsgRep\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x04R\x05msgId2\xac\x06\n" +
	"\vChatService\x12H\n" +
	"\x12SendPrivateMessage\x12\x1b.chat.SendPrivateMessageReq\x1a\x15.chat.SendMessageResp\x12D\n" +
	"\x10SendGroupMessage\x12\x19.chat.SendGroupMessageReq\x1a\x15.chat.SendMessageResp\x12N\n" +
	"\x15GetHistoryChatMessage\x12\x1f.chat.GetChatHistoryMessagesReq\x1a\x14.chat.CommonResponse\x12Q\n" +
	"\x17GetHistoryGroupMessages\x12 .chat.GetGroupHistoryMessagesReq\x1a\x14.chat.CommonResponse\x12L\n" +
	"\x14GetUnreadChatMessage\x12\x1e.chat.GetChatUnreadMessagesReq\x1a\x14.chat.CommonResponse\x12O\n" +
	"\x16GetUnreadGroupMessages\x12\x1f.chat.GetGroupUnreadMessagesReq\x1a\x14.chat.CommonResponse\x12X\n" +
	"\x17GetNewChatMessageNumber\x12!.chat.GetChatNewMessagesNumberReq\x1a\x1a.chat.GetMessageNumberResp\x12Z\n" +
	"\x18GetNewGroupMessageNumber\x12\".chat.GetGroupNewMessagesNumberReq\x1a\x1a.chat.GetMessageNumberResp\x12I\n" +
	"\x15UpdateChatMsgLastRead\x12\x1a.chat.UpdateLastReadMsgRep\x1a\x14.chat.CommonResponse\x12J\n" +
	"\x16UpdataGroupMsgLastRead\x12\x1a.chat.UpdateLastReadMsgRep\x1a\x14.chat.CommonResponseB\bZ\x06./chatb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_chat_proto_goTypes = []any{
	(*CommonResponse)(nil),               // 0: chat.CommonResponse
	(*SendPrivateMessageReq)(nil),        // 1: chat.SendPrivateMessageReq
	(*SendGroupMessageReq)(nil),          // 2: chat.SendGroupMessageReq
	(*SendMessageResp)(nil),              // 3: chat.SendMessageResp
	(*GetChatHistoryMessagesReq)(nil),    // 4: chat.GetChatHistoryMessagesReq
	(*GetGroupHistoryMessagesReq)(nil),   // 5: chat.GetGroupHistoryMessagesReq
	(*GetChatUnreadMessagesReq)(nil),     // 6: chat.GetChatUnreadMessagesReq
	(*GetGroupUnreadMessagesReq)(nil),    // 7: chat.GetGroupUnreadMessagesReq
	(*GetChatNewMessagesNumberReq)(nil),  // 8: chat.GetChatNewMessagesNumberReq
	(*GetGroupNewMessagesNumberReq)(nil), // 9: chat.GetGroupNewMessagesNumberReq
	(*Unread)(nil),                       // 10: chat.unread
	(*GetMessageNumberResp)(nil),         // 11: chat.GetMessageNumberResp
	(*UpdateLastReadMsgRep)(nil),         // 12: chat.UpdateLastReadMsgRep
}
var file_chat_proto_depIdxs = []int32{
	0,  // 0: chat.SendMessageResp.CommonResponse:type_name -> chat.CommonResponse
	10, // 1: chat.GetMessageNumberResp.list:type_name -> chat.unread
	1,  // 2: chat.ChatService.SendPrivateMessage:input_type -> chat.SendPrivateMessageReq
	2,  // 3: chat.ChatService.SendGroupMessage:input_type -> chat.SendGroupMessageReq
	4,  // 4: chat.ChatService.GetHistoryChatMessage:input_type -> chat.GetChatHistoryMessagesReq
	5,  // 5: chat.ChatService.GetHistoryGroupMessages:input_type -> chat.GetGroupHistoryMessagesReq
	6,  // 6: chat.ChatService.GetUnreadChatMessage:input_type -> chat.GetChatUnreadMessagesReq
	7,  // 7: chat.ChatService.GetUnreadGroupMessages:input_type -> chat.GetGroupUnreadMessagesReq
	8,  // 8: chat.ChatService.GetNewChatMessageNumber:input_type -> chat.GetChatNewMessagesNumberReq
	9,  // 9: chat.ChatService.GetNewGroupMessageNumber:input_type -> chat.GetGroupNewMessagesNumberReq
	12, // 10: chat.ChatService.UpdateChatMsgLastRead:input_type -> chat.UpdateLastReadMsgRep
	12, // 11: chat.ChatService.UpdataGroupMsgLastRead:input_type -> chat.UpdateLastReadMsgRep
	3,  // 12: chat.ChatService.SendPrivateMessage:output_type -> chat.SendMessageResp
	3,  // 13: chat.ChatService.SendGroupMessage:output_type -> chat.SendMessageResp
	0,  // 14: chat.ChatService.GetHistoryChatMessage:output_type -> chat.CommonResponse
	0,  // 15: chat.ChatService.GetHistoryGroupMessages:output_type -> chat.CommonResponse
	0,  // 16: chat.ChatService.GetUnreadChatMessage:output_type -> chat.CommonResponse
	0,  // 17: chat.ChatService.GetUnreadGroupMessages:output_type -> chat.CommonResponse
	11, // 18: chat.ChatService.GetNewChatMessageNumber:output_type -> chat.GetMessageNumberResp
	11, // 19: chat.ChatService.GetNewGroupMessageNumber:output_type -> chat.GetMessageNumberResp
	0,  // 20: chat.ChatService.UpdateChatMsgLastRead:output_type -> chat.CommonResponse
	0,  // 21: chat.ChatService.UpdataGroupMsgLastRead:output_type -> chat.CommonResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
