// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: relation.proto

package relation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==================== 枚举定义 ====================
type FriendStatus int32

const (
	FriendStatus_FRIEND_STATUS_UNSPECIFIED FriendStatus = 0 // 申请中
	FriendStatus_FRIEND_STATUS_ACCEPTED    FriendStatus = 1 // 已通过
	FriendStatus_FRIEND_STATUS_REJECTED    FriendStatus = 2 // 已拒绝
	FriendStatus_FRIEND_STATUS_BLOCKED     FriendStatus = 3 // 已删除
)

// Enum value maps for FriendStatus.
var (
	FriendStatus_name = map[int32]string{
		0: "FRIEND_STATUS_UNSPECIFIED",
		1: "FRIEND_STATUS_ACCEPTED",
		2: "FRIEND_STATUS_REJECTED",
		3: "FRIEND_STATUS_BLOCKED",
	}
	FriendStatus_value = map[string]int32{
		"FRIEND_STATUS_UNSPECIFIED": 0,
		"FRIEND_STATUS_ACCEPTED":    1,
		"FRIEND_STATUS_REJECTED":    2,
		"FRIEND_STATUS_BLOCKED":     3,
	}
)

func (x FriendStatus) Enum() *FriendStatus {
	p := new(FriendStatus)
	*p = x
	return p
}

func (x FriendStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_relation_proto_enumTypes[0].Descriptor()
}

func (FriendStatus) Type() protoreflect.EnumType {
	return &file_relation_proto_enumTypes[0]
}

func (x FriendStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendStatus.Descriptor instead.
func (FriendStatus) EnumDescriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{0}
}

type GroupMemberRole int32

const (
	GroupMemberRole_MEMBER_ROLE_UNSPECIFIED GroupMemberRole = 0
	GroupMemberRole_MEMBER_ROLE_MEMBER      GroupMemberRole = 1 // 普通成员
	GroupMemberRole_MEMBER_ROLE_ADMIN       GroupMemberRole = 2 // 管理员
	GroupMemberRole_MEMBER_ROLE_OWNER       GroupMemberRole = 3 // 群主
)

// Enum value maps for GroupMemberRole.
var (
	GroupMemberRole_name = map[int32]string{
		0: "MEMBER_ROLE_UNSPECIFIED",
		1: "MEMBER_ROLE_MEMBER",
		2: "MEMBER_ROLE_ADMIN",
		3: "MEMBER_ROLE_OWNER",
	}
	GroupMemberRole_value = map[string]int32{
		"MEMBER_ROLE_UNSPECIFIED": 0,
		"MEMBER_ROLE_MEMBER":      1,
		"MEMBER_ROLE_ADMIN":       2,
		"MEMBER_ROLE_OWNER":       3,
	}
)

func (x GroupMemberRole) Enum() *GroupMemberRole {
	p := new(GroupMemberRole)
	*p = x
	return p
}

func (x GroupMemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupMemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_relation_proto_enumTypes[1].Descriptor()
}

func (GroupMemberRole) Type() protoreflect.EnumType {
	return &file_relation_proto_enumTypes[1]
}

func (x GroupMemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupMemberRole.Descriptor instead.
func (GroupMemberRole) EnumDescriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{1}
}

type GroupMemberStatus int32

const (
	GroupMemberStatus_MEMBER_STATUS_UNSPECIFIED GroupMemberStatus = 0
	GroupMemberStatus_MEMBER_STATUS_ACTIVE      GroupMemberStatus = 1 // 已加入
	GroupMemberStatus_MEMBER_STATUS_PENDING     GroupMemberStatus = 2 // 申请中
	GroupMemberStatus_MEMBER_STATUS_REJECTED    GroupMemberStatus = 3 // 申请被拒
	GroupMemberStatus_MEMBER_STATUS_KICKED      GroupMemberStatus = 4 // 被移除
	GroupMemberStatus_MEMBER_STATUS_LEFT        GroupMemberStatus = 5 // 主动退出
)

// Enum value maps for GroupMemberStatus.
var (
	GroupMemberStatus_name = map[int32]string{
		0: "MEMBER_STATUS_UNSPECIFIED",
		1: "MEMBER_STATUS_ACTIVE",
		2: "MEMBER_STATUS_PENDING",
		3: "MEMBER_STATUS_REJECTED",
		4: "MEMBER_STATUS_KICKED",
		5: "MEMBER_STATUS_LEFT",
	}
	GroupMemberStatus_value = map[string]int32{
		"MEMBER_STATUS_UNSPECIFIED": 0,
		"MEMBER_STATUS_ACTIVE":      1,
		"MEMBER_STATUS_PENDING":     2,
		"MEMBER_STATUS_REJECTED":    3,
		"MEMBER_STATUS_KICKED":      4,
		"MEMBER_STATUS_LEFT":        5,
	}
)

func (x GroupMemberStatus) Enum() *GroupMemberStatus {
	p := new(GroupMemberStatus)
	*p = x
	return p
}

func (x GroupMemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupMemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_relation_proto_enumTypes[2].Descriptor()
}

func (GroupMemberStatus) Type() protoreflect.EnumType {
	return &file_relation_proto_enumTypes[2]
}

func (x GroupMemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupMemberStatus.Descriptor instead.
func (GroupMemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{2}
}

// ==================== 通用响应 ====================
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0 成功，非0错误码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 返回消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ==================== 分页 ====================
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 页码，从1开始
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{2}
}

func (x *PageInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ==================== 好友相关消息 ====================
type FriendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                  // 记录ID
	FriendName    string                 `protobuf:"bytes,2,opt,name=friend_name,json=friendName,proto3" json:"friend_name,omitempty"` // 好友名
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`                           // 备注名
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`                           // 头像
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                     // 签名
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday      int64                  `protobuf:"varint,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	LastOnline    int64                  `protobuf:"varint,8,opt,name=last_online,json=lastOnline,proto3" json:"last_online,omitempty"`    // 上次在线时间
	OnlineStatu   bool                   `protobuf:"varint,9,opt,name=online_statu,json=onlineStatu,proto3" json:"online_statu,omitempty"` // 在线状态
	Status        FriendStatus           `protobuf:"varint,10,opt,name=status,proto3,enum=relation.FriendStatus" json:"status,omitempty"`  // 状态
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // 建立时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	mi := &file_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{3}
}

func (x *FriendInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendInfo) GetFriendName() string {
	if x != nil {
		return x.FriendName
	}
	return ""
}

func (x *FriendInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FriendInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *FriendInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *FriendInfo) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

func (x *FriendInfo) GetLastOnline() int64 {
	if x != nil {
		return x.LastOnline
	}
	return 0
}

func (x *FriendInfo) GetOnlineStatu() bool {
	if x != nil {
		return x.OnlineStatu
	}
	return false
}

func (x *FriendInfo) GetStatus() FriendStatus {
	if x != nil {
		return x.Status
	}
	return FriendStatus_FRIEND_STATUS_UNSPECIFIED
}

func (x *FriendInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 搜索用户
type SearchUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchName    string                 `protobuf:"bytes,1,opt,name=search_name,json=searchName,proto3" json:"search_name,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserReq) Reset() {
	*x = SearchUserReq{}
	mi := &file_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserReq) ProtoMessage() {}

func (x *SearchUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserReq.ProtoReflect.Descriptor instead.
func (*SearchUserReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUserReq) GetSearchName() string {
	if x != nil {
		return x.SearchName
	}
	return ""
}

func (x *SearchUserReq) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type SearchUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CommonResponse        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	List          []*FriendInfo          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"` // 搜索到的用户
	Page          *PageInfo              `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserResp) Reset() {
	*x = SearchUserResp{}
	mi := &file_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserResp) ProtoMessage() {}

func (x *SearchUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserResp.ProtoReflect.Descriptor instead.
func (*SearchUserResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{5}
}

func (x *SearchUserResp) GetBase() *CommonResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *SearchUserResp) GetList() []*FriendInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SearchUserResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// 发送好友请求
type SendFriendRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 发起方
	FriendId      uint64                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 接收方
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`                            // 附言（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestReq) Reset() {
	*x = SendFriendRequestReq{}
	mi := &file_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestReq) ProtoMessage() {}

func (x *SendFriendRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestReq.ProtoReflect.Descriptor instead.
func (*SendFriendRequestReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{6}
}

func (x *SendFriendRequestReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendFriendRequestReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *SendFriendRequestReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SendFriendRequestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CommonResponse        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 生成的好友记录ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResp) Reset() {
	*x = SendFriendRequestResp{}
	mi := &file_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResp) ProtoMessage() {}

func (x *SendFriendRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResp.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{7}
}

func (x *SendFriendRequestResp) GetBase() *CommonResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *SendFriendRequestResp) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// 处理好友请求（同意/拒绝）
type HandleFriendRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 好友记录ID
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`                        // true同意，false拒绝
	SenderId      uint64                 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`    // 发起者ID
	HandlerId     uint64                 `protobuf:"varint,4,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"` // 操作者ID（必须是被请求方）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestReq) Reset() {
	*x = HandleFriendRequestReq{}
	mi := &file_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestReq) ProtoMessage() {}

func (x *HandleFriendRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestReq.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{8}
}

func (x *HandleFriendRequestReq) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *HandleFriendRequestReq) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *HandleFriendRequestReq) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *HandleFriendRequestReq) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type HandleFriendRequestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CommonResponse        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestResp) Reset() {
	*x = HandleFriendRequestResp{}
	mi := &file_relation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestResp) ProtoMessage() {}

func (x *HandleFriendRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestResp.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{9}
}

func (x *HandleFriendRequestResp) GetBase() *CommonResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

// 删除好友
type DeleteFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      uint64                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendReq) Reset() {
	*x = DeleteFriendReq{}
	mi := &file_relation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendReq) ProtoMessage() {}

func (x *DeleteFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendReq.ProtoReflect.Descriptor instead.
func (*DeleteFriendReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFriendReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFriendReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

// 设置好友备注
type SetFriendRemarkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      uint64                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFriendRemarkReq) Reset() {
	*x = SetFriendRemarkReq{}
	mi := &file_relation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFriendRemarkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFriendRemarkReq) ProtoMessage() {}

func (x *SetFriendRemarkReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFriendRemarkReq.ProtoReflect.Descriptor instead.
func (*SetFriendRemarkReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{11}
}

func (x *SetFriendRemarkReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetFriendRemarkReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *SetFriendRemarkReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 获取好友列表（仅已通过）
type GetFriendListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListReq) Reset() {
	*x = GetFriendListReq{}
	mi := &file_relation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListReq) ProtoMessage() {}

func (x *GetFriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListReq.ProtoReflect.Descriptor instead.
func (*GetFriendListReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{12}
}

func (x *GetFriendListReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFriendListReq) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetFriendListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CommonResponse        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	List          []*FriendInfo          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListResp) Reset() {
	*x = GetFriendListResp{}
	mi := &file_relation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListResp) ProtoMessage() {}

func (x *GetFriendListResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListResp.ProtoReflect.Descriptor instead.
func (*GetFriendListResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{13}
}

func (x *GetFriendListResp) GetBase() *CommonResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetFriendListResp) GetList() []*FriendInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetFriendListResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// 获取好友请求列表（待处理的，即别人发给我的）
type GetFriendRequestsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前用户，作为接收方
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsReq) Reset() {
	*x = GetFriendRequestsReq{}
	mi := &file_relation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsReq) ProtoMessage() {}

func (x *GetFriendRequestsReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsReq.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{14}
}

func (x *GetFriendRequestsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFriendRequestsReq) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetFriendRequestsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CommonResponse        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	List          []*FriendInfo          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"` // status=PENDING的记录
	Page          *PageInfo              `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsResp) Reset() {
	*x = GetFriendRequestsResp{}
	mi := &file_relation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsResp) ProtoMessage() {}

func (x *GetFriendRequestsResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsResp.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{15}
}

func (x *GetFriendRequestsResp) GetBase() *CommonResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetFriendRequestsResp) GetList() []*FriendInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetFriendRequestsResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// ==================== 群组相关消息 ====================
type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Notice        string                 `protobuf:"bytes,5,opt,name=notice,proto3" json:"notice,omitempty"`
	MemberCount   int32                  `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_relation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{16}
}

func (x *GroupInfo) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GroupInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupInfo) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *GroupInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GroupInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GroupInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 创建群组
type CreateGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Notice        string                 `protobuf:"bytes,4,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	mi := &file_relation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{17}
}

func (x *CreateGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupReq) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateGroupReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateGroupReq) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

type CreateGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CommonResponse        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResp) Reset() {
	*x = CreateGroupResp{}
	mi := &file_relation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResp) ProtoMessage() {}

func (x *CreateGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResp.ProtoReflect.Descriptor instead.
func (*CreateGroupResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{18}
}

func (x *CreateGroupResp) GetBase() *CommonResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateGroupResp) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 更新群信息
type UpdateGroupInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    uint64                 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者，需为群主或管理员
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                // 空则不更新
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Notice        string                 `protobuf:"bytes,5,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupInfoReq) Reset() {
	*x = UpdateGroupInfoReq{}
	mi := &file_relation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoReq) ProtoMessage() {}

func (x *UpdateGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateGroupInfoReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *UpdateGroupInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateGroupInfoReq) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

// 解散群组
type DismissGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // 仅群主可操作
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupReq) Reset() {
	*x = DismissGroupReq{}
	mi := &file_relation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupReq) ProtoMessage() {}

func (x *DismissGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupReq.ProtoReflect.Descriptor instead.
func (*DismissGroupReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{20}
}

func (x *DismissGroupReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DismissGroupReq) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

// 获取群信息
type GetGroupInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ViewerId      uint64                 `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"` // 查看者ID，用于权限校验（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoReq) Reset() {
	*x = GetGroupInfoReq{}
	mi := &file_relation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoReq) ProtoMessage() {}

func (x *GetGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoReq.ProtoReflect.Descriptor instead.
func (*GetGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{21}
}

func (x *GetGroupInfoReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupInfoReq) GetViewerId() uint64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

type GetGroupInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CommonResponse        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Info          *GroupInfo             `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoResp) Reset() {
	*x = GetGroupInfoResp{}
	mi := &file_relation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoResp) ProtoMessage() {}

func (x *GetGroupInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoResp.ProtoReflect.Descriptor instead.
func (*GetGroupInfoResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{22}
}

func (x *GetGroupInfoResp) GetBase() *CommonResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetGroupInfoResp) GetInfo() *GroupInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// ==================== 群成员相关消息 ====================
type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 记录ID
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          GroupMemberRole        `protobuf:"varint,4,opt,name=role,proto3,enum=relation.GroupMemberRole" json:"role,omitempty"`
	GroupNick     string                 `protobuf:"bytes,5,opt,name=group_nick,json=groupNick,proto3" json:"group_nick,omitempty"` // 群昵称
	Status        GroupMemberStatus      `protobuf:"varint,6,opt,name=status,proto3,enum=relation.GroupMemberStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_relation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{23}
}

func (x *GroupMember) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMember) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMember) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMember) GetRole() GroupMemberRole {
	if x != nil {
		return x.Role
	}
	return GroupMemberRole_MEMBER_ROLE_UNSPECIFIED
}

func (x *GroupMember) GetGroupNick() string {
	if x != nil {
		return x.GroupNick
	}
	return ""
}

func (x *GroupMember) GetStatus() GroupMemberStatus {
	if x != nil {
		return x.Status
	}
	return GroupMemberStatus_MEMBER_STATUS_UNSPECIFIED
}

func (x *GroupMember) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GroupMember) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 申请加入群组
type ApplyToJoinGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 申请附言
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyToJoinGroupReq) Reset() {
	*x = ApplyToJoinGroupReq{}
	mi := &file_relation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyToJoinGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyToJoinGroupReq) ProtoMessage() {}

func (x *ApplyToJoinGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyToJoinGroupReq.ProtoReflect.Descriptor instead.
func (*ApplyToJoinGroupReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{24}
}

func (x *ApplyToJoinGroupReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ApplyToJoinGroupReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApplyToJoinGroupReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 处理群加入申请（同意/拒绝）
type ProcessGroupJoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ApplicantId   uint64                 `protobuf:"varint,2,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"` // 申请人ID
	OperatorId    uint64                 `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`    // 群主或管理员
	Accept        bool                   `protobuf:"varint,4,opt,name=accept,proto3" json:"accept,omitempty"`                              // true同意，false拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessGroupJoinReq) Reset() {
	*x = ProcessGroupJoinReq{}
	mi := &file_relation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessGroupJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessGroupJoinReq) ProtoMessage() {}

func (x *ProcessGroupJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessGroupJoinReq.ProtoReflect.Descriptor instead.
func (*ProcessGroupJoinReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{25}
}

func (x *ProcessGroupJoinReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ProcessGroupJoinReq) GetApplicantId() uint64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *ProcessGroupJoinReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *ProcessGroupJoinReq) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

// 邀请加入群组（直接加入，无需申请）
type InviteToGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	InviterId     uint64                 `protobuf:"varint,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`           // 邀请人
	InviteeIds    []uint64               `protobuf:"varint,3,rep,packed,name=invitee_ids,json=inviteeIds,proto3" json:"invitee_ids,omitempty"` // 被邀请人列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteToGroupReq) Reset() {
	*x = InviteToGroupReq{}
	mi := &file_relation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteToGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteToGroupReq) ProtoMessage() {}

func (x *InviteToGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteToGroupReq.ProtoReflect.Descriptor instead.
func (*InviteToGroupReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{26}
}

func (x *InviteToGroupReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *InviteToGroupReq) GetInviterId() uint64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *InviteToGroupReq) GetInviteeIds() []uint64 {
	if x != nil {
		return x.InviteeIds
	}
	return nil
}

// 退出群组
type QuitGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitGroupReq) Reset() {
	*x = QuitGroupReq{}
	mi := &file_relation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitGroupReq) ProtoMessage() {}

func (x *QuitGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitGroupReq.ProtoReflect.Descriptor instead.
func (*QuitGroupReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{27}
}

func (x *QuitGroupReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *QuitGroupReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 移除群成员
type RemoveGroupMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    uint64                 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 群主或管理员
	TargetId      uint64                 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`       // 被移除成员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupMemberReq) Reset() {
	*x = RemoveGroupMemberReq{}
	mi := &file_relation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberReq) ProtoMessage() {}

func (x *RemoveGroupMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberReq.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{28}
}

func (x *RemoveGroupMemberReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RemoveGroupMemberReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *RemoveGroupMemberReq) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 设置群成员角色（设为管理员/取消管理员）
type SetGroupMemberRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    uint64                 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 群主或管理员
	TargetId      uint64                 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	NewRole       GroupMemberRole        `protobuf:"varint,4,opt,name=new_role,json=newRole,proto3,enum=relation.GroupMemberRole" json:"new_role,omitempty"` // 只能设为MEMBER或ADMIN（不能设为OWNER）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupMemberRoleReq) Reset() {
	*x = SetGroupMemberRoleReq{}
	mi := &file_relation_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupMemberRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupMemberRoleReq) ProtoMessage() {}

func (x *SetGroupMemberRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupMemberRoleReq.ProtoReflect.Descriptor instead.
func (*SetGroupMemberRoleReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{29}
}

func (x *SetGroupMemberRoleReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SetGroupMemberRoleReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *SetGroupMemberRoleReq) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SetGroupMemberRoleReq) GetNewRole() GroupMemberRole {
	if x != nil {
		return x.NewRole
	}
	return GroupMemberRole_MEMBER_ROLE_UNSPECIFIED
}

// 设置群昵称
type SetGroupNickReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupNick     string                 `protobuf:"bytes,3,opt,name=group_nick,json=groupNick,proto3" json:"group_nick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupNickReq) Reset() {
	*x = SetGroupNickReq{}
	mi := &file_relation_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupNickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupNickReq) ProtoMessage() {}

func (x *SetGroupNickReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupNickReq.ProtoReflect.Descriptor instead.
func (*SetGroupNickReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{30}
}

func (x *SetGroupNickReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SetGroupNickReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetGroupNickReq) GetGroupNick() string {
	if x != nil {
		return x.GroupNick
	}
	return ""
}

// 获取群成员列表（仅active状态）
type GetGroupMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersReq) Reset() {
	*x = GetGroupMembersReq{}
	mi := &file_relation_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersReq) ProtoMessage() {}

func (x *GetGroupMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersReq.ProtoReflect.Descriptor instead.
func (*GetGroupMembersReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{31}
}

func (x *GetGroupMembersReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupMembersReq) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetGroupMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CommonResponse        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	List          []*GroupMember         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersResp) Reset() {
	*x = GetGroupMembersResp{}
	mi := &file_relation_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersResp) ProtoMessage() {}

func (x *GetGroupMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersResp.ProtoReflect.Descriptor instead.
func (*GetGroupMembersResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{32}
}

func (x *GetGroupMembersResp) GetBase() *CommonResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetGroupMembersResp) GetList() []*GroupMember {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetGroupMembersResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// 获取群加入申请列表（待处理的，即status=PENDING）
type GetGroupJoinRequestsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    uint64                 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 群主或管理员
	Page          *PageRequest           `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupJoinRequestsReq) Reset() {
	*x = GetGroupJoinRequestsReq{}
	mi := &file_relation_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupJoinRequestsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupJoinRequestsReq) ProtoMessage() {}

func (x *GetGroupJoinRequestsReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupJoinRequestsReq.ProtoReflect.Descriptor instead.
func (*GetGroupJoinRequestsReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{33}
}

func (x *GetGroupJoinRequestsReq) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupJoinRequestsReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *GetGroupJoinRequestsReq) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetGroupJoinRequestsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CommonResponse        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	List          []*GroupMember         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"` // 只返回PENDING状态的成员记录
	Page          *PageInfo              `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupJoinRequestsResp) Reset() {
	*x = GetGroupJoinRequestsResp{}
	mi := &file_relation_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupJoinRequestsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupJoinRequestsResp) ProtoMessage() {}

func (x *GetGroupJoinRequestsResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupJoinRequestsResp.ProtoReflect.Descriptor instead.
func (*GetGroupJoinRequestsResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{34}
}

func (x *GetGroupJoinRequestsResp) GetBase() *CommonResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetGroupJoinRequestsResp) GetList() []*GroupMember {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetGroupJoinRequestsResp) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_relation_proto protoreflect.FileDescriptor

const file_relation_proto_rawDesc = "" +
	"\n" +
	"\x0erelation.proto\x12\brelation\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"5\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"H\n" +
	"\bPageInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"\xd2\x02\n" +
	"\n" +
	"FriendInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vfriend_name\x18\x02 \x01(\tR\n" +
	"friendName\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x1a\n" +
	"\bbirthday\x18\a \x01(\x03R\bbirthday\x12\x1f\n" +
	"\vlast_online\x18\b \x01(\x03R\n" +
	"lastOnline\x12!\n" +
	"\fonline_statu\x18\t \x01(\bR\vonlineStatu\x12.\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x16.relation.FriendStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\"[\n" +
	"\rSearchUserReq\x12\x1f\n" +
	"\vsearch_name\x18\x01 \x01(\tR\n" +
	"searchName\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.relation.PageRequestR\x04page\"\x90\x01\n" +
	"\x0eSearchUserResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.relation.CommonResponseR\x04base\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.relation.FriendInfoR\x04list\x12&\n" +
	"\x04page\x18\x03 \x01(\v2\x12.relation.PageInfoR\x04page\"^\n" +
	"\x14SendFriendRequestReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x04R\bfriendId\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"d\n" +
	"\x15SendFriendRequestResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.relation.CommonResponseR\x04base\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\"\x8b\x01\n" +
	"\x16HandleFriendRequestReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x04R\bsenderId\x12\x1d\n" +
	"\n" +
	"handler_id\x18\x04 \x01(\x04R\thandlerId\"G\n" +
	"\x17HandleFriendRequestResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.relation.CommonResponseR\x04base\"G\n" +
	"\x0fDeleteFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x04R\bfriendId\"b\n" +
	"\x12SetFriendRemarkReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x04R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"V\n" +
	"\x10GetFriendListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.relation.PageRequestR\x04page\"\x93\x01\n" +
	"\x11GetFriendListResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.relation.CommonResponseR\x04base\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.relation.FriendInfoR\x04list\x12&\n" +
	"\x04page\x18\x03 \x01(\v2\x12.relation.PageInfoR\x04page\"Z\n" +
	"\x14GetFriendRequestsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.relation.PageRequestR\x04page\"\x97\x01\n" +
	"\x15GetFriendRequestsResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.relation.CommonResponseR\x04base\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.relation.FriendInfoR\x04list\x12&\n" +
	"\x04page\x18\x03 \x01(\v2\x12.relation.PageInfoR\x04page\"\x9e\x02\n" +
	"\tGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x04R\aownerId\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06notice\x18\x05 \x01(\tR\x06notice\x12!\n" +
	"\fmember_count\x18\x06 \x01(\x05R\vmemberCount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"o\n" +
	"\x0eCreateGroupReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x04R\aownerId\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06notice\x18\x04 \x01(\tR\x06notice\"Z\n" +
	"\x0fCreateGroupResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.relation.CommonResponseR\x04base\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\"\x94\x01\n" +
	"\x12UpdateGroupInfoReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x04R\n" +
	"operatorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06notice\x18\x05 \x01(\tR\x06notice\"G\n" +
	"\x0fDismissGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x04R\aownerId\"I\n" +
	"\x0fGetGroupInfoReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\x04R\bviewerId\"i\n" +
	"\x10GetGroupInfoResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.relation.CommonResponseR\x04base\x12'\n" +
	"\x04info\x18\x02 \x01(\v2\x13.relation.GroupInfoR\x04info\"\xca\x02\n" +
	"\vGroupMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12-\n" +
	"\x04role\x18\x04 \x01(\x0e2\x19.relation.GroupMemberRoleR\x04role\x12\x1d\n" +
	"\n" +
	"group_nick\x18\x05 \x01(\tR\tgroupNick\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.relation.GroupMemberStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"c\n" +
	"\x13ApplyToJoinGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8c\x01\n" +
	"\x13ProcessGroupJoinReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12!\n" +
	"\fapplicant_id\x18\x02 \x01(\x04R\vapplicantId\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x04R\n" +
	"operatorId\x12\x16\n" +
	"\x06accept\x18\x04 \x01(\bR\x06accept\"m\n" +
	"\x10InviteToGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x02 \x01(\x04R\tinviterId\x12\x1f\n" +
	"\vinvitee_ids\x18\x03 \x03(\x04R\n" +
	"inviteeIds\"B\n" +
	"\fQuitGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"o\n" +
	"\x14RemoveGroupMemberReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x04R\n" +
	"operatorId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x04R\btargetId\"\xa6\x01\n" +
	"\x15SetGroupMemberRoleReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x04R\n" +
	"operatorId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x04R\btargetId\x124\n" +
	"\bnew_role\x18\x04 \x01(\x0e2\x19.relation.GroupMemberRoleR\anewRole\"d\n" +
	"\x0fSetGroupNickReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"group_nick\x18\x03 \x01(\tR\tgroupNick\"Z\n" +
	"\x12GetGroupMembersReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.relation.PageRequestR\x04page\"\x96\x01\n" +
	"\x13GetGroupMembersResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.relation.CommonResponseR\x04base\x12)\n" +
	"\x04list\x18\x02 \x03(\v2\x15.relation.GroupMemberR\x04list\x12&\n" +
	"\x04page\x18\x03 \x01(\v2\x12.relation.PageInfoR\x04page\"\x80\x01\n" +
	"\x17GetGroupJoinRequestsReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x04R\n" +
	"operatorId\x12)\n" +
	"\x04page\x18\x03 \x01(\v2\x15.relation.PageRequestR\x04page\"\x9b\x01\n" +
	"\x18GetGroupJoinRequestsResp\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.relation.CommonResponseR\x04base\x12)\n" +
	"\x04list\x18\x02 \x03(\v2\x15.relation.GroupMemberR\x04list\x12&\n" +
	"\x04page\x18\x03 \x01(\v2\x12.relation.PageInfoR\x04page*\x80\x01\n" +
	"\fFriendStatus\x12\x1d\n" +
	"\x19FRIEND_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FRIEND_STATUS_ACCEPTED\x10\x01\x12\x1a\n" +
	"\x16FRIEND_STATUS_REJECTED\x10\x02\x12\x19\n" +
	"\x15FRIEND_STATUS_BLOCKED\x10\x03*t\n" +
	"\x0fGroupMemberRole\x12\x1b\n" +
	"\x17MEMBER_ROLE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MEMBER_ROLE_MEMBER\x10\x01\x12\x15\n" +
	"\x11MEMBER_ROLE_ADMIN\x10\x02\x12\x15\n" +
	"\x11MEMBER_ROLE_OWNER\x10\x03*\xb5\x01\n" +
	"\x11GroupMemberStatus\x12\x1d\n" +
	"\x19MEMBER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MEMBER_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15MEMBER_STATUS_PENDING\x10\x02\x12\x1a\n" +
	"\x16MEMBER_STATUS_REJECTED\x10\x03\x12\x18\n" +
	"\x14MEMBER_STATUS_KICKED\x10\x04\x12\x16\n" +
	"\x12MEMBER_STATUS_LEFT\x10\x052\xb2\x04\n" +
	"\rFriendService\x12T\n" +
	"\x11SendFriendRequest\x12\x1e.relation.SendFriendRequestReq\x1a\x1f.relation.SendFriendRequestResp\x12Z\n" +
	"\x13HandleFriendRequest\x12 .relation.HandleFriendRequestReq\x1a!.relation.HandleFriendRequestResp\x12C\n" +
	"\fDeleteFriend\x12\x19.relation.DeleteFriendReq\x1a\x18.relation.CommonResponse\x12I\n" +
	"\x0fSetFriendRemark\x12\x1c.relation.SetFriendRemarkReq\x1a\x18.relation.CommonResponse\x12H\n" +
	"\rGetFriendList\x12\x1a.relation.GetFriendListReq\x1a\x1b.relation.GetFriendListResp\x12T\n" +
	"\x11GetFriendRequests\x12\x1e.relation.GetFriendRequestsReq\x1a\x1f.relation.GetFriendRequestsResp\x12?\n" +
	"\n" +
	"SearchUser\x12\x17.relation.SearchUserReq\x1a\x18.relation.SearchUserResp2\xa9\x02\n" +
	"\fGroupService\x12B\n" +
	"\vCreateGroup\x12\x18.relation.CreateGroupReq\x1a\x19.relation.CreateGroupResp\x12I\n" +
	"\x0fUpdateGroupInfo\x12\x1c.relation.UpdateGroupInfoReq\x1a\x18.relation.CommonResponse\x12C\n" +
	"\fDismissGroup\x12\x19.relation.DismissGroupReq\x1a\x18.relation.CommonResponse\x12E\n" +
	"\fGetGroupInfo\x12\x19.relation.GetGroupInfoReq\x1a\x1a.relation.GetGroupInfoResp2\xc8\x05\n" +
	"\x12GroupMemberService\x12K\n" +
	"\x10ApplyToJoinGroup\x12\x1d.relation.ApplyToJoinGroupReq\x1a\x18.relation.CommonResponse\x12K\n" +
	"\x10ProcessGroupJoin\x12\x1d.relation.ProcessGroupJoinReq\x1a\x18.relation.CommonResponse\x12E\n" +
	"\rInviteToGroup\x12\x1a.relation.InviteToGroupReq\x1a\x18.relation.CommonResponse\x12=\n" +
	"\tQuitGroup\x12\x16.relation.QuitGroupReq\x1a\x18.relation.CommonResponse\x12M\n" +
	"\x11RemoveGroupMember\x12\x1e.relation.RemoveGroupMemberReq\x1a\x18.relation.CommonResponse\x12O\n" +
	"\x12SetGroupMemberRole\x12\x1f.relation.SetGroupMemberRoleReq\x1a\x18.relation.CommonResponse\x12C\n" +
	"\fSetGroupNick\x12\x19.relation.SetGroupNickReq\x1a\x18.relation.CommonResponse\x12N\n" +
	"\x0fGetGroupMembers\x12\x1c.relation.GetGroupMembersReq\x1a\x1d.relation.GetGroupMembersResp\x12]\n" +
	"\x14GetGroupJoinRequests\x12!.relation.GetGroupJoinRequestsReq\x1a\".relation.GetGroupJoinRequestsRespB\fZ\n" +
	"./relationb\x06proto3"

var (
	file_relation_proto_rawDescOnce sync.Once
	file_relation_proto_rawDescData []byte
)

func file_relation_proto_rawDescGZIP() []byte {
	file_relation_proto_rawDescOnce.Do(func() {
		file_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)))
	})
	return file_relation_proto_rawDescData
}

var file_relation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_relation_proto_goTypes = []any{
	(FriendStatus)(0),                // 0: relation.FriendStatus
	(GroupMemberRole)(0),             // 1: relation.GroupMemberRole
	(GroupMemberStatus)(0),           // 2: relation.GroupMemberStatus
	(*CommonResponse)(nil),           // 3: relation.CommonResponse
	(*PageRequest)(nil),              // 4: relation.PageRequest
	(*PageInfo)(nil),                 // 5: relation.PageInfo
	(*FriendInfo)(nil),               // 6: relation.FriendInfo
	(*SearchUserReq)(nil),            // 7: relation.SearchUserReq
	(*SearchUserResp)(nil),           // 8: relation.SearchUserResp
	(*SendFriendRequestReq)(nil),     // 9: relation.SendFriendRequestReq
	(*SendFriendRequestResp)(nil),    // 10: relation.SendFriendRequestResp
	(*HandleFriendRequestReq)(nil),   // 11: relation.HandleFriendRequestReq
	(*HandleFriendRequestResp)(nil),  // 12: relation.HandleFriendRequestResp
	(*DeleteFriendReq)(nil),          // 13: relation.DeleteFriendReq
	(*SetFriendRemarkReq)(nil),       // 14: relation.SetFriendRemarkReq
	(*GetFriendListReq)(nil),         // 15: relation.GetFriendListReq
	(*GetFriendListResp)(nil),        // 16: relation.GetFriendListResp
	(*GetFriendRequestsReq)(nil),     // 17: relation.GetFriendRequestsReq
	(*GetFriendRequestsResp)(nil),    // 18: relation.GetFriendRequestsResp
	(*GroupInfo)(nil),                // 19: relation.GroupInfo
	(*CreateGroupReq)(nil),           // 20: relation.CreateGroupReq
	(*CreateGroupResp)(nil),          // 21: relation.CreateGroupResp
	(*UpdateGroupInfoReq)(nil),       // 22: relation.UpdateGroupInfoReq
	(*DismissGroupReq)(nil),          // 23: relation.DismissGroupReq
	(*GetGroupInfoReq)(nil),          // 24: relation.GetGroupInfoReq
	(*GetGroupInfoResp)(nil),         // 25: relation.GetGroupInfoResp
	(*GroupMember)(nil),              // 26: relation.GroupMember
	(*ApplyToJoinGroupReq)(nil),      // 27: relation.ApplyToJoinGroupReq
	(*ProcessGroupJoinReq)(nil),      // 28: relation.ProcessGroupJoinReq
	(*InviteToGroupReq)(nil),         // 29: relation.InviteToGroupReq
	(*QuitGroupReq)(nil),             // 30: relation.QuitGroupReq
	(*RemoveGroupMemberReq)(nil),     // 31: relation.RemoveGroupMemberReq
	(*SetGroupMemberRoleReq)(nil),    // 32: relation.SetGroupMemberRoleReq
	(*SetGroupNickReq)(nil),          // 33: relation.SetGroupNickReq
	(*GetGroupMembersReq)(nil),       // 34: relation.GetGroupMembersReq
	(*GetGroupMembersResp)(nil),      // 35: relation.GetGroupMembersResp
	(*GetGroupJoinRequestsReq)(nil),  // 36: relation.GetGroupJoinRequestsReq
	(*GetGroupJoinRequestsResp)(nil), // 37: relation.GetGroupJoinRequestsResp
	(*timestamppb.Timestamp)(nil),    // 38: google.protobuf.Timestamp
}
var file_relation_proto_depIdxs = []int32{
	0,  // 0: relation.FriendInfo.status:type_name -> relation.FriendStatus
	4,  // 1: relation.SearchUserReq.page:type_name -> relation.PageRequest
	3,  // 2: relation.SearchUserResp.base:type_name -> relation.CommonResponse
	6,  // 3: relation.SearchUserResp.list:type_name -> relation.FriendInfo
	5,  // 4: relation.SearchUserResp.page:type_name -> relation.PageInfo
	3,  // 5: relation.SendFriendRequestResp.base:type_name -> relation.CommonResponse
	3,  // 6: relation.HandleFriendRequestResp.base:type_name -> relation.CommonResponse
	4,  // 7: relation.GetFriendListReq.page:type_name -> relation.PageRequest
	3,  // 8: relation.GetFriendListResp.base:type_name -> relation.CommonResponse
	6,  // 9: relation.GetFriendListResp.list:type_name -> relation.FriendInfo
	5,  // 10: relation.GetFriendListResp.page:type_name -> relation.PageInfo
	4,  // 11: relation.GetFriendRequestsReq.page:type_name -> relation.PageRequest
	3,  // 12: relation.GetFriendRequestsResp.base:type_name -> relation.CommonResponse
	6,  // 13: relation.GetFriendRequestsResp.list:type_name -> relation.FriendInfo
	5,  // 14: relation.GetFriendRequestsResp.page:type_name -> relation.PageInfo
	38, // 15: relation.GroupInfo.created_at:type_name -> google.protobuf.Timestamp
	38, // 16: relation.GroupInfo.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 17: relation.CreateGroupResp.base:type_name -> relation.CommonResponse
	3,  // 18: relation.GetGroupInfoResp.base:type_name -> relation.CommonResponse
	19, // 19: relation.GetGroupInfoResp.info:type_name -> relation.GroupInfo
	1,  // 20: relation.GroupMember.role:type_name -> relation.GroupMemberRole
	2,  // 21: relation.GroupMember.status:type_name -> relation.GroupMemberStatus
	38, // 22: relation.GroupMember.created_at:type_name -> google.protobuf.Timestamp
	38, // 23: relation.GroupMember.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 24: relation.SetGroupMemberRoleReq.new_role:type_name -> relation.GroupMemberRole
	4,  // 25: relation.GetGroupMembersReq.page:type_name -> relation.PageRequest
	3,  // 26: relation.GetGroupMembersResp.base:type_name -> relation.CommonResponse
	26, // 27: relation.GetGroupMembersResp.list:type_name -> relation.GroupMember
	5,  // 28: relation.GetGroupMembersResp.page:type_name -> relation.PageInfo
	4,  // 29: relation.GetGroupJoinRequestsReq.page:type_name -> relation.PageRequest
	3,  // 30: relation.GetGroupJoinRequestsResp.base:type_name -> relation.CommonResponse
	26, // 31: relation.GetGroupJoinRequestsResp.list:type_name -> relation.GroupMember
	5,  // 32: relation.GetGroupJoinRequestsResp.page:type_name -> relation.PageInfo
	9,  // 33: relation.FriendService.SendFriendRequest:input_type -> relation.SendFriendRequestReq
	11, // 34: relation.FriendService.HandleFriendRequest:input_type -> relation.HandleFriendRequestReq
	13, // 35: relation.FriendService.DeleteFriend:input_type -> relation.DeleteFriendReq
	14, // 36: relation.FriendService.SetFriendRemark:input_type -> relation.SetFriendRemarkReq
	15, // 37: relation.FriendService.GetFriendList:input_type -> relation.GetFriendListReq
	17, // 38: relation.FriendService.GetFriendRequests:input_type -> relation.GetFriendRequestsReq
	7,  // 39: relation.FriendService.SearchUser:input_type -> relation.SearchUserReq
	20, // 40: relation.GroupService.CreateGroup:input_type -> relation.CreateGroupReq
	22, // 41: relation.GroupService.UpdateGroupInfo:input_type -> relation.UpdateGroupInfoReq
	23, // 42: relation.GroupService.DismissGroup:input_type -> relation.DismissGroupReq
	24, // 43: relation.GroupService.GetGroupInfo:input_type -> relation.GetGroupInfoReq
	27, // 44: relation.GroupMemberService.ApplyToJoinGroup:input_type -> relation.ApplyToJoinGroupReq
	28, // 45: relation.GroupMemberService.ProcessGroupJoin:input_type -> relation.ProcessGroupJoinReq
	29, // 46: relation.GroupMemberService.InviteToGroup:input_type -> relation.InviteToGroupReq
	30, // 47: relation.GroupMemberService.QuitGroup:input_type -> relation.QuitGroupReq
	31, // 48: relation.GroupMemberService.RemoveGroupMember:input_type -> relation.RemoveGroupMemberReq
	32, // 49: relation.GroupMemberService.SetGroupMemberRole:input_type -> relation.SetGroupMemberRoleReq
	33, // 50: relation.GroupMemberService.SetGroupNick:input_type -> relation.SetGroupNickReq
	34, // 51: relation.GroupMemberService.GetGroupMembers:input_type -> relation.GetGroupMembersReq
	36, // 52: relation.GroupMemberService.GetGroupJoinRequests:input_type -> relation.GetGroupJoinRequestsReq
	10, // 53: relation.FriendService.SendFriendRequest:output_type -> relation.SendFriendRequestResp
	12, // 54: relation.FriendService.HandleFriendRequest:output_type -> relation.HandleFriendRequestResp
	3,  // 55: relation.FriendService.DeleteFriend:output_type -> relation.CommonResponse
	3,  // 56: relation.FriendService.SetFriendRemark:output_type -> relation.CommonResponse
	16, // 57: relation.FriendService.GetFriendList:output_type -> relation.GetFriendListResp
	18, // 58: relation.FriendService.GetFriendRequests:output_type -> relation.GetFriendRequestsResp
	8,  // 59: relation.FriendService.SearchUser:output_type -> relation.SearchUserResp
	21, // 60: relation.GroupService.CreateGroup:output_type -> relation.CreateGroupResp
	3,  // 61: relation.GroupService.UpdateGroupInfo:output_type -> relation.CommonResponse
	3,  // 62: relation.GroupService.DismissGroup:output_type -> relation.CommonResponse
	25, // 63: relation.GroupService.GetGroupInfo:output_type -> relation.GetGroupInfoResp
	3,  // 64: relation.GroupMemberService.ApplyToJoinGroup:output_type -> relation.CommonResponse
	3,  // 65: relation.GroupMemberService.ProcessGroupJoin:output_type -> relation.CommonResponse
	3,  // 66: relation.GroupMemberService.InviteToGroup:output_type -> relation.CommonResponse
	3,  // 67: relation.GroupMemberService.QuitGroup:output_type -> relation.CommonResponse
	3,  // 68: relation.GroupMemberService.RemoveGroupMember:output_type -> relation.CommonResponse
	3,  // 69: relation.GroupMemberService.SetGroupMemberRole:output_type -> relation.CommonResponse
	3,  // 70: relation.GroupMemberService.SetGroupNick:output_type -> relation.CommonResponse
	35, // 71: relation.GroupMemberService.GetGroupMembers:output_type -> relation.GetGroupMembersResp
	37, // 72: relation.GroupMemberService.GetGroupJoinRequests:output_type -> relation.GetGroupJoinRequestsResp
	53, // [53:73] is the sub-list for method output_type
	33, // [33:53] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_relation_proto_init() }
func file_relation_proto_init() {
	if File_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_relation_proto_goTypes,
		DependencyIndexes: file_relation_proto_depIdxs,
		EnumInfos:         file_relation_proto_enumTypes,
		MessageInfos:      file_relation_proto_msgTypes,
	}.Build()
	File_relation_proto = out.File
	file_relation_proto_goTypes = nil
	file_relation_proto_depIdxs = nil
}
